import { Opportunity } from "./types";

export const SEED_OPPORTUNITIES: Opportunity[] = [
  {
    id: "1",
    type: "athlete",
    sport: "Football",
    name: "Marcus Rashford",
    meta: "Manchester United & England forward. 28M social followers. Strong youth & education advocacy.",
    trend_dir: "up",
    reach: "28M",
    geo: ["UK", "Global"],
    excl: true,
    cat_fit: { sportswear: 95, fintech: 70, automotive: 80, fmcg: 75, luxury: 85, education: 90 },
    audience: { income_score: 72, real_follower_pct: 81, age_18_34_pct: 64, female_pct: 38 },
    budget_min: 500000,
    budget_max: 2000000,
    tags: ["ambassador", "social impact", "youth"],
    highlights: ["Child food poverty campaigner — earned MBE", "Top 10 PL shirt sales globally", "Nike athlete with co-creation line"],
    risks: ["Recent form dip", "Tabloid attention risk"],
    partners: ["Nike", "Burberry"],
    rights: ["Image", "Social posts", "Event appearances", "Product co-design"],
  },
  {
    id: "2",
    type: "club",
    sport: "Football",
    name: "FC Barcelona",
    meta: "Global football club. 350M+ social followers. Iconic brand with 'Més que un club' ethos.",
    trend_dir: "up",
    reach: "350M",
    geo: ["Spain", "Global", "LATAM", "USA"],
    excl: false,
    cat_fit: { sportswear: 95, fintech: 80, automotive: 85, fmcg: 70, luxury: 90, tech: 85 },
    audience: { income_score: 68, real_follower_pct: 74, age_18_34_pct: 58, female_pct: 32 },
    budget_min: 5000000,
    budget_max: 50000000,
    tags: ["shirt sponsor", "stadium naming", "sleeve"],
    highlights: ["Largest social following in sport", "New Spotify Camp Nou reopening 2025", "La Masia pipeline drives constant narrative"],
    risks: ["Financial restructuring history", "Crowded sponsor portfolio"],
    partners: ["Nike", "Spotify", "Ambrosia"],
    rights: ["Shirt front/back/sleeve", "LED boards", "Hospitality suites", "Digital content series"],
  },
  {
    id: "3",
    type: "event",
    sport: "Tennis",
    name: "Wimbledon Championships",
    meta: "The oldest and most prestigious tennis tournament. 2-week grass-court Grand Slam.",
    trend_dir: "flat",
    reach: "1B",
    geo: ["UK", "Global"],
    excl: true,
    cat_fit: { luxury: 95, automotive: 90, fintech: 75, fmcg: 80, sportswear: 70, beverages: 90 },
    audience: { income_score: 89, real_follower_pct: 92, age_18_34_pct: 42, female_pct: 52 },
    budget_min: 2000000,
    budget_max: 15000000,
    tags: ["premium", "heritage", "hospitality"],
    highlights: ["Royal patronage & global broadcast", "Premium demographic — ABC1 skew", "Limited partner roster = high exclusivity"],
    risks: ["Weather dependency", "Short 2-week activation window", "Strict brand guidelines"],
    partners: ["Rolex", "Ralph Lauren", "Jaguar", "Lavazza"],
    rights: ["Courtside signage", "Hospitality pavilion", "Official supplier status", "Digital activations"],
  },
  {
    id: "4",
    type: "league",
    sport: "Basketball",
    name: "NBA",
    meta: "Premier basketball league. 30 teams. Massive global youth appeal and digital-first strategy.",
    trend_dir: "up",
    reach: "2B",
    geo: ["USA", "Global", "China", "Europe"],
    excl: false,
    cat_fit: { sportswear: 95, tech: 90, fintech: 80, fmcg: 75, automotive: 70, entertainment: 90 },
    audience: { income_score: 75, real_follower_pct: 78, age_18_34_pct: 72, female_pct: 35 },
    budget_min: 10000000,
    budget_max: 100000000,
    tags: ["league partner", "all-star", "digital"],
    highlights: ["Youngest major sport demographic", "League-wide jersey patch program", "NBA Africa & NBA India expansion"],
    risks: ["High entry cost", "Player controversy exposure", "Competitive category congestion"],
    partners: ["Nike", "Kia", "State Farm", "Google"],
    rights: ["League-wide branding", "All-Star Weekend activation", "NBA App integration", "Player access pool"],
  },
  {
    id: "5",
    type: "grassroots",
    sport: "Football",
    name: "Street League UK",
    meta: "Charity using football to help young people into jobs, training & education across 12 UK cities.",
    trend_dir: "up",
    reach: "200K",
    geo: ["UK"],
    excl: true,
    cat_fit: { fmcg: 80, fintech: 70, education: 95, sportswear: 75, tech: 65, beverages: 70 },
    audience: { income_score: 45, real_follower_pct: 88, age_18_34_pct: 90, female_pct: 40 },
    budget_min: 50000,
    budget_max: 500000,
    tags: ["CSR", "youth", "community", "ESG"],
    highlights: ["84% of participants move into employment", "Operates in 12 UK cities", "Strong ESG narrative for annual reports"],
    risks: ["Limited broadcast exposure", "Requires long-term commitment for ROI"],
    partners: ["Nike", "Barclays"],
    rights: ["Title naming", "Kit branding", "Impact reports co-branding", "Participant mentoring access"],
  },
  {
    id: "6",
    type: "athlete",
    sport: "Tennis",
    name: "Emma Raducanu",
    meta: "British tennis star. US Open champion. Dual Chinese-Romanian heritage boosts APAC appeal.",
    trend_dir: "up",
    reach: "5M",
    geo: ["UK", "USA", "China", "Global"],
    excl: true,
    cat_fit: { luxury: 95, automotive: 90, fintech: 75, sportswear: 80, beauty: 90, tech: 70 },
    audience: { income_score: 82, real_follower_pct: 85, age_18_34_pct: 68, female_pct: 58 },
    budget_min: 1000000,
    budget_max: 5000000,
    tags: ["ambassador", "APAC crossover", "Gen Z icon"],
    highlights: ["Historic US Open win at 18", "Multi-ethnic heritage = APAC + European appeal", "Porsche, Dior, British Airways ambassador"],
    risks: ["Injury history concerns", "Results inconsistency post-US Open"],
    partners: ["Porsche", "Dior", "British Airways", "HSBC"],
    rights: ["Image", "Social content", "Event appearances", "Product collaboration"],
  },
  {
    id: "7",
    type: "event",
    sport: "Multi-sport",
    name: "Olympic Games LA 2028",
    meta: "The world's largest multi-sport event. Expected 4B+ global viewers. LA 2028 edition.",
    trend_dir: "up",
    reach: "4B",
    geo: ["USA", "Global"],
    excl: true,
    cat_fit: { sportswear: 95, tech: 90, automotive: 85, fmcg: 80, luxury: 75, fintech: 70, beverages: 90 },
    audience: { income_score: 70, real_follower_pct: 90, age_18_34_pct: 55, female_pct: 50 },
    budget_min: 50000000,
    budget_max: 200000000,
    tags: ["TOP sponsor", "national", "ambush risk"],
    highlights: ["Unrivalled global reach & prestige", "LA venue = entertainment crossover potential", "Sustainability-first narrative"],
    risks: ["Massive minimum investment", "Strict Rule 40 limits athlete activation", "Geopolitical boycott risk"],
    partners: ["Coca-Cola", "Samsung", "Toyota", "Visa", "P&G"],
    rights: ["TOP Programme branding", "Athlete village presence", "Broadcast idents", "Torch relay sponsor"],
  },
  {
    id: "8",
    type: "club",
    sport: "Football",
    name: "Wrexham AFC",
    meta: "Welsh football club owned by Ryan Reynolds & Rob McElhenney. Viral 'Welcome to Wrexham' docuseries.",
    trend_dir: "up",
    reach: "15M",
    geo: ["UK", "USA", "Global"],
    excl: true,
    cat_fit: { entertainment: 95, fmcg: 85, beverages: 90, tech: 70, automotive: 65, sportswear: 60 },
    audience: { income_score: 65, real_follower_pct: 72, age_18_34_pct: 60, female_pct: 44 },
    budget_min: 200000,
    budget_max: 2000000,
    tags: ["storytelling", "underdog", "entertainment crossover"],
    highlights: ["Disney+ docuseries = unique media exposure", "Hollywood ownership attracts non-traditional fans", "Rapid on-pitch rise through leagues"],
    risks: ["Small stadium limits matchday activation", "Novelty factor may plateau"],
    partners: ["TikTok", "Aviation Gin", "Expedia"],
    rights: ["Shirt sponsor", "Docuseries integration", "Social content", "Stadium branding"],
  },
  {
    id: "9",
    type: "athlete",
    sport: "Golf",
    name: "Nelly Korda",
    meta: "World #1 women's golfer. 6 LPGA wins in 2024. Olympic gold medallist. Huge US appeal.",
    trend_dir: "up",
    reach: "2M",
    geo: ["USA", "Global"],
    excl: true,
    cat_fit: { luxury: 90, automotive: 85, fintech: 80, sportswear: 75, beauty: 85, beverages: 65 },
    audience: { income_score: 88, real_follower_pct: 90, age_18_34_pct: 48, female_pct: 55 },
    budget_min: 500000,
    budget_max: 3000000,
    tags: ["women's sport", "premium", "Olympic"],
    highlights: ["Dominated 2024 LPGA season", "Olympic gold adds multi-sport narrative", "Premium golf demographic aligns with luxury/auto"],
    risks: ["Golf viewership still niche vs. mainstream sport", "Endorsement market maturing for women's golf"],
    partners: ["Callaway", "J. Lindeberg"],
    rights: ["Image", "Social content", "Tournament hospitality", "Equipment branding"],
  },
  {
    id: "10",
    type: "league",
    sport: "Football",
    name: "Premier League",
    meta: "Most-watched football league globally. 20 clubs. 4.7B cumulative TV audience per season.",
    trend_dir: "flat",
    reach: "4.7B",
    geo: ["UK", "Global", "Asia", "Africa", "Americas"],
    excl: false,
    cat_fit: { sportswear: 90, fintech: 85, automotive: 80, fmcg: 85, tech: 80, beverages: 90 },
    audience: { income_score: 65, real_follower_pct: 70, age_18_34_pct: 55, female_pct: 30 },
    budget_min: 10000000,
    budget_max: 80000000,
    tags: ["league partner", "broadcast", "global"],
    highlights: ["Broadcast in 189 countries", "High emotional engagement week-on-week", "Fantasy Premier League = 11M+ active users"],
    risks: ["Fixture congestion dilutes attention", "Fan backlash against over-commercialisation"],
    partners: ["EA Sports", "Barclays", "Hublot", "Oracle"],
    rights: ["Broadcast idents", "Matchday branding", "FPL integration", "Community programmes"],
  },
  {
    id: "11",
    type: "grassroots",
    sport: "Running",
    name: "parkrun Global",
    meta: "Free weekly 5K events in 22 countries. 9M+ registered runners. Community health movement.",
    trend_dir: "up",
    reach: "9M",
    geo: ["UK", "Australia", "USA", "Global"],
    excl: true,
    cat_fit: { sportswear: 90, fmcg: 80, beverages: 85, fintech: 60, health: 95, tech: 70 },
    audience: { income_score: 72, real_follower_pct: 95, age_18_34_pct: 38, female_pct: 55 },
    budget_min: 500000,
    budget_max: 5000000,
    tags: ["community", "health", "weekly activation", "ESG"],
    highlights: ["9M+ participants across 22 countries", "Weekly recurring = sustained brand visibility", "Strong NHS/public health alignment in UK"],
    risks: ["Volunteer-run = brand control limitations", "Anti-commercialisation ethos among core base"],
    partners: ["Vitality", "Brooks Running"],
    rights: ["Event naming", "Kit branding", "Finish token branding", "App integration"],
  },
  {
    id: "12",
    type: "athlete",
    sport: "Athletics",
    name: "Sydney McLaughlin-Levrone",
    meta: "World record holder 400m hurdles. Olympic double gold. Dominant force in track & field.",
    trend_dir: "up",
    reach: "3.5M",
    geo: ["USA", "Global"],
    excl: true,
    cat_fit: { sportswear: 95, beauty: 80, health: 85, tech: 70, luxury: 75, education: 70 },
    audience: { income_score: 70, real_follower_pct: 88, age_18_34_pct: 72, female_pct: 62 },
    budget_min: 300000,
    budget_max: 2000000,
    tags: ["Olympic", "record-holder", "women's sport", "faith-based"],
    highlights: ["Owns world record — generational talent", "Best-selling author (Far Beyond Gold)", "Clean, family-friendly brand image"],
    risks: ["Track & field limited mainstream visibility outside Olympics", "Faith-based positioning may narrow brand fit"],
    partners: ["New Balance", "Gatorade", "Oakley"],
    rights: ["Image", "Social content", "Training content", "Event appearances"],
  },
  {
    id: "13",
    type: "event",
    sport: "Motorsport",
    name: "Formula 1 — Las Vegas Grand Prix",
    meta: "Night race on the Las Vegas Strip. Launched 2023 to massive entertainment crossover.",
    trend_dir: "up",
    reach: "500M",
    geo: ["USA", "Global"],
    excl: false,
    cat_fit: { luxury: 95, automotive: 95, tech: 85, beverages: 90, entertainment: 95, fintech: 75 },
    audience: { income_score: 85, real_follower_pct: 78, age_18_34_pct: 62, female_pct: 38 },
    budget_min: 2000000,
    budget_max: 20000000,
    tags: ["premium", "night race", "entertainment", "hospitality"],
    highlights: ["Strip backdrop = unmatched visual spectacle", "Celeb-heavy attendance drives cultural relevance", "F1 US growth fuelled by Drive to Survive"],
    risks: ["Early-stage event — ROI benchmarks still forming", "High hospitality costs for activation"],
    partners: ["Heineken", "Las Vegas Tourism", "T-Mobile"],
    rights: ["Trackside signage", "Paddock Club hospitality", "Fan zone activation", "Broadcast package"],
  },
  {
    id: "14",
    type: "club",
    sport: "Basketball",
    name: "Golden State Warriors",
    meta: "NBA franchise. 4x recent champions. Silicon Valley HQ = unique tech crossover.",
    trend_dir: "flat",
    reach: "50M",
    geo: ["USA", "China", "Global"],
    excl: false,
    cat_fit: { tech: 95, fintech: 85, sportswear: 80, entertainment: 80, automotive: 70, luxury: 75 },
    audience: { income_score: 80, real_follower_pct: 76, age_18_34_pct: 65, female_pct: 35 },
    budget_min: 5000000,
    budget_max: 30000000,
    tags: ["tech crossover", "dynasty", "global fanbase"],
    highlights: ["Chase Center = state-of-the-art venue", "Steph Curry = all-time marketing asset", "Silicon Valley location = unique B2B opportunities"],
    risks: ["Dynasty narrative ageing as roster turns over", "Bay Area market = expensive activation costs"],
    partners: ["Rakuten", "Chase", "Kaiser Permanente"],
    rights: ["Jersey patch", "Arena naming", "Courtside signage", "Digital content", "Suite hospitality"],
  },
  {
    id: "15",
    type: "grassroots",
    sport: "Cycling",
    name: "HSBC UK Breeze",
    meta: "UK's biggest women-only cycling programme. 100K+ rides delivered. Breaking barriers in women's cycling.",
    trend_dir: "flat",
    reach: "150K",
    geo: ["UK"],
    excl: true,
    cat_fit: { health: 95, sportswear: 80, fmcg: 70, beverages: 65, automotive: 60, fintech: 55 },
    audience: { income_score: 68, real_follower_pct: 92, age_18_34_pct: 35, female_pct: 95 },
    budget_min: 100000,
    budget_max: 750000,
    tags: ["women's sport", "community", "wellbeing", "ESG"],
    highlights: ["100K+ women reached through guided rides", "Strong DEI narrative for brand reporting", "British Cycling backing = credibility"],
    risks: ["Niche scale vs. mainstream sponsorships", "Weather-dependent participation"],
    partners: ["HSBC"],
    rights: ["Programme naming", "Kit branding", "Event signage", "Impact storytelling"],
  },
  {
    id: "16",
    type: "athlete",
    sport: "Football",
    name: "Leah Williamson",
    meta: "Arsenal & England captain. Led Lionesses to Euro 2022 triumph. Key voice in women's football.",
    trend_dir: "up",
    reach: "1.5M",
    geo: ["UK", "Europe"],
    excl: true,
    cat_fit: { sportswear: 85, beauty: 80, luxury: 70, education: 75, fmcg: 70, fintech: 65 },
    audience: { income_score: 65, real_follower_pct: 90, age_18_34_pct: 70, female_pct: 65 },
    budget_min: 150000,
    budget_max: 800000,
    tags: ["women's sport", "captain", "role model"],
    highlights: ["Lifted Euro 2022 trophy — iconic moment", "Articulate, media-trained, brand-safe", "Growing influence beyond football"],
    risks: ["ACL injury history", "Women's football commercial market still growing"],
    partners: ["Nike", "Pepsi", "Gucci"],
    rights: ["Image", "Social content", "Campaign work", "Speaking engagements"],
  },
  {
    id: "17",
    type: "event",
    sport: "Cricket",
    name: "IPL — Indian Premier League",
    meta: "T20 cricket league. Richest cricket competition. 500M+ viewers per season. BCCI owned.",
    trend_dir: "up",
    reach: "500M",
    geo: ["India", "South Asia", "UK", "Global"],
    excl: false,
    cat_fit: { tech: 85, fintech: 90, fmcg: 90, automotive: 80, beverages: 90, luxury: 65 },
    audience: { income_score: 55, real_follower_pct: 68, age_18_34_pct: 65, female_pct: 28 },
    budget_min: 5000000,
    budget_max: 50000000,
    tags: ["India", "mass market", "entertainment", "T20"],
    highlights: ["India market access at scale", "Celebrity team owners = cultural crossover", "Digital-first broadcast via JioCinema"],
    risks: ["Cluttered sponsor environment", "Match-fixing legacy perception", "Regulatory complexity in India"],
    partners: ["Tata", "Dream11", "CEAT", "Jio"],
    rights: ["Title sponsor", "Team sponsor", "Boundary branding", "Strategic timeout partner"],
  },
  {
    id: "18",
    type: "athlete",
    sport: "Basketball",
    name: "Caitlin Clark",
    meta: "WNBA Indiana Fever guard. NCAA all-time scoring leader. Transforming women's basketball viewership.",
    trend_dir: "up",
    reach: "8M",
    geo: ["USA"],
    excl: false,
    cat_fit: { sportswear: 90, fmcg: 80, tech: 75, fintech: 70, beverages: 85, entertainment: 80 },
    audience: { income_score: 62, real_follower_pct: 82, age_18_34_pct: 78, female_pct: 52 },
    budget_min: 500000,
    budget_max: 3000000,
    tags: ["women's sport", "record-breaker", "Gen Z", "cultural moment"],
    highlights: ["Shattered NCAA viewership records", "Nike signature shoe in development", "Driving unprecedented WNBA attendance"],
    risks: ["Intense media scrutiny creates volatility", "Young career = limited track record"],
    partners: ["Nike", "Gatorade", "State Farm"],
    rights: ["Image", "Social content", "Event appearances", "Product collaboration"],
  },
  {
    id: "19",
    type: "league",
    sport: "Football",
    name: "MLS — Major League Soccer",
    meta: "US & Canadian football league. 30 clubs. Fast growth via Messi effect and Apple TV deal.",
    trend_dir: "up",
    reach: "100M",
    geo: ["USA", "Canada", "LATAM"],
    excl: false,
    cat_fit: { fmcg: 80, automotive: 75, tech: 80, fintech: 70, sportswear: 75, beverages: 85 },
    audience: { income_score: 68, real_follower_pct: 70, age_18_34_pct: 62, female_pct: 36 },
    budget_min: 2000000,
    budget_max: 20000000,
    tags: ["US growth", "streaming", "multicultural"],
    highlights: ["Apple TV deal = innovative media model", "Messi & ex-European stars drive interest", "Hispanic community engagement unmatched"],
    risks: ["Still building mainstream US relevance vs NFL/NBA", "Franchise quality inconsistent"],
    partners: ["Adidas", "Apple TV", "Audi", "AT&T"],
    rights: ["League branding", "Broadcast integration", "All-Star activation", "Community programmes"],
  },
  {
    id: "20",
    type: "event",
    sport: "Rugby",
    name: "Six Nations Championship",
    meta: "Annual rugby union tournament. England, France, Ireland, Italy, Scotland, Wales. Premium European sport.",
    trend_dir: "flat",
    reach: "120M",
    geo: ["UK", "Ireland", "France", "Italy", "Europe"],
    excl: true,
    cat_fit: { beverages: 90, automotive: 85, luxury: 80, fintech: 75, fmcg: 80, sportswear: 70 },
    audience: { income_score: 78, real_follower_pct: 85, age_18_34_pct: 45, female_pct: 35 },
    budget_min: 3000000,
    budget_max: 15000000,
    tags: ["heritage", "premium", "multi-market", "hospitality"],
    highlights: ["Passionate multi-national fanbase", "Premium hospitality market", "Strong pub/broadcast viewing culture"],
    risks: ["Fixture calendar limited to Feb-Mar window", "Fragmented rights across nations"],
    partners: ["Guinness", "Jaguar Land Rover"],
    rights: ["Title sponsor", "Matchday branding", "Hospitality", "Broadcast idents", "Digital content"],
  },
];
