-- IVY Opportunities Seed Data
-- 300 opportunities across athletes, clubs, events, leagues, grassroots
-- Run in Supabase SQL editor or via migration

truncate table opportunities restart identity cascade;

insert into opportunities (type, sport, name, meta, trend_dir, reach, geo, excl, cat_fit, audience, budget_min, budget_max, tags, highlights, risks, partners, rights) values

-- ─── FOOTBALL ATHLETES ────────────────────────────────────────────────────────
('athlete','football','Kylian Mbappé','Real Madrid · French · Age 26','up','420M',array['global'],false,'{"luxury":82,"sportswear":96,"finance":55,"auto":70,"tech":65,"energy":78,"fmcg":72,"hospitality":68}','{"y1834":62,"female":42,"income":82,"real":91}',2000000,8000000,array['Highest reach','38% Asia','Champions League'],array['120M+ followers — largest individual platform in sport','38% Asia audience — ideal for APAC market entry','Champions League profile guarantees peak media exposure all season'],array['Nike exclusivity blocks sportswear category','Reputation risk following PSG exit'],array['Nike','Dior','Hublot'],array['Social','Campaign','Appearances']),

('athlete','football','Erling Haaland','Manchester City · Norwegian · Age 24','up','85M',array['europe','asia'],false,'{"luxury":74,"sportswear":92,"finance":58,"auto":72,"tech":68,"energy":94,"fmcg":78,"hospitality":65}','{"y1834":64,"female":38,"income":74,"real":89}',1500000,5000000,array['Premier League record scorer','Energy score 94','Youth audience'],array['Premier League all-time record scorer — peak media moment','Energy score 94 — strongest in sport for nutrition brands','64% aged 18–34 — strong Gen Z reach'],array['Red Bull partnership limits energy category','Nike holds sportswear'],array['Nike','Red Bull','Audi'],array['Social','Campaign','Events']),

('athlete','football','Lamine Yamal','FC Barcelona · Spanish · Age 17','up','52M',array['europe','asia','americas'],true,'{"luxury":72,"sportswear":90,"finance":48,"auto":55,"tech":82,"energy":86,"fmcg":80,"hospitality":60}','{"y1834":78,"female":40,"income":64,"real":92}',800000,3000000,array['Gen Z icon','Fastest rising','All slots open'],array['Youngest Ballon d''Or contender — defining the next decade of sport','78% aged 18–34 — strongest Gen Z reach in football','All category slots open — early mover advantage is significant'],array['Age creates contractual complexity','Long-term trajectory not yet proven'],array['Adidas','Gatorade'],array['Social','Campaign','Kit','Events']),

('athlete','football','Vinícius Jr.','Real Madrid · Brazilian · Age 24','up','95M',array['global'],false,'{"luxury":78,"sportswear":92,"finance":58,"auto":68,"tech":72,"energy":80,"fmcg":74,"hospitality":68}','{"y1834":65,"female":41,"income":76,"real":88}',1200000,4500000,array['Ballon d''Or podium','Brazil reach','Champions League winner'],array['Ballon d''Or podium — peak global recognition moment','Strong Brazil and Latin America audience expands Americas reach','Champions League winner — elite brand association guaranteed'],array['Racism controversies require ongoing brand risk management','Nike holds primary sportswear'],array['Nike','Amstel'],array['Social','Campaign','Appearances']),

('athlete','football','Jude Bellingham','Real Madrid · English · Age 21','up','55M',array['europe','americas'],true,'{"luxury":80,"sportswear":90,"finance":65,"auto":70,"tech":78,"energy":75,"fmcg":70,"hospitality":72}','{"y1834":66,"female":40,"income":78,"real":90}',1000000,4000000,array['England icon','Real Madrid','Multiple slots open'],array['Youngest key Real Madrid player in 30 years','Strong UK and Europe equity with growing Americas audience','Multiple slots available across luxury, finance and tech'],array['Still building global brand outside Europe','Tommy Hilfiger holds fashion-adjacent space'],array['Tommy Hilfiger','EA Sports'],array['Social','Campaign','Appearances']),

('athlete','football','Mohamed Salah','Liverpool FC · Egyptian · Age 32','flat','92M',array['europe','asia','mena'],false,'{"luxury":76,"sportswear":86,"finance":72,"auto":68,"tech":70,"energy":72,"fmcg":80,"hospitality":72}','{"y1834":55,"female":36,"income":76,"real":87}',1000000,3500000,array['MENA reach premium','Premier League icon','FMCG affinity'],array['Dominant MENA audience reach — unique in Premier League','Premier League all-time top scorer — sustained brand equity','Strong FMCG audience affinity through Egyptian fan base'],array['Age 32 — career trajectory watch','Contract expiry uncertainty'],array['Adidas','Pepsi','Western Union'],array['Social','Campaign','Appearances']),

('athlete','football','Harry Kane','Bayern Munich · English · Age 31','flat','38M',array['europe','americas'],true,'{"luxury":78,"sportswear":84,"finance":74,"auto":72,"tech":68,"energy":68,"fmcg":76,"hospitality":74}','{"y1834":52,"female":34,"income":80,"real":88}',800000,3000000,array['Bundesliga record scorer','Category slots open','UK brand equity'],array['Bundesliga record scorer — peak German market exposure window','Strong UK heritage — premium British brand positioning','Multiple category slots available outside sportswear'],array['England captaincy performance scrutiny','Lower social following vs peers'],array['Adidas','Skechers'],array['Social','Campaign','Appearances']),

('athlete','football','Pedri','FC Barcelona · Spanish · Age 22','up','22M',array['europe','asia'],true,'{"luxury":76,"sportswear":84,"finance":60,"auto":65,"tech":76,"energy":72,"fmcg":68,"hospitality":68}','{"y1834":68,"female":42,"income":72,"real":91}',500000,2000000,array['Barcelona future','68% under 35','Affordable entry'],array['Spain''s defining midfield talent — 10-year brand horizon','68% aged 18–34 — exceptional youth audience','Low entry cost with significant upside'],array['Injury history creates activation risk','Building global profile outside Spain'],array['Nike','Audi'],array['Social','Campaign','Kit']),

('athlete','football','Rodri','Manchester City · Spanish · Age 28','up','14M',array['europe','asia'],true,'{"luxury":74,"sportswear":80,"finance":68,"auto":70,"tech":70,"energy":68,"fmcg":68,"hospitality":70}','{"y1834":50,"female":34,"income":76,"real":88}',600000,2200000,array['Ballon d''Or winner','Category slots open','Cerebral brand fit'],array['2024 Ballon d''Or winner — peak recognition','Category slots available across finance and tech','Thoughtful, intelligent persona — premium brand alignment'],array['Injury return timing uncertain','Lower social following vs attackers'],array['Adidas'],array['Social','Campaign','Appearances']),

('athlete','football','Phil Foden','Manchester City · English · Age 24','up','18M',array['europe','americas'],true,'{"luxury":74,"sportswear":86,"finance":64,"auto":68,"tech":74,"energy":72,"fmcg":72,"hospitality":68}','{"y1834":64,"female":38,"income":74,"real":89}',600000,2500000,array['England star','City academy product','Youth audience'],array['Premier League winner and England regular','Authentic academy story — local hero narrative','64% aged 18–34 — strong youth demographic'],array['Puma holds sportswear','Still building global brand'],array['Puma'],array['Social','Campaign','Appearances']),

('athlete','football','Bukayo Saka','Arsenal FC · English · Age 23','up','20M',array['europe','asia','americas'],true,'{"luxury":72,"sportswear":88,"finance":66,"auto":68,"tech":76,"energy":72,"fmcg":74,"hospitality":68}','{"y1834":66,"female":38,"income":74,"real":91}',600000,2500000,array['Arsenal icon','England starter','Gen Z reach'],array['Arsenal''s most important player — brand tied to club''s rise','England regular — World Cup profile growing','66% aged 18–34 — excellent Gen Z reach'],array['Nike holds sportswear'],array['Nike','Toffee Crisp'],array['Social','Campaign','Appearances']),

('athlete','football','Gavi','FC Barcelona · Spanish · Age 20','flat','12M',array['europe'],true,'{"luxury":68,"sportswear":82,"finance":56,"auto":58,"tech":72,"energy":70,"fmcg":68,"hospitality":62}','{"y1834":72,"female":40,"income":68,"real":90}',400000,1500000,array['Barcelona captain','Youth icon','Low cost'],array['Barcelona captain at 20 — exceptional brand horizon','72% aged 18–34 — one of the youngest audiences in football','Low entry cost with long-term upside'],array['Injury history — return not guaranteed','Limited global following outside Spain'],array['Adidas'],array['Social','Campaign','Kit']),

('athlete','football','Declan Rice','Arsenal FC · English · Age 26','up','16M',array['europe','americas'],true,'{"luxury":72,"sportswear":84,"finance":68,"auto":68,"tech":72,"energy":72,"fmcg":72,"hospitality":68}','{"y1834":58,"female":34,"income":74,"real":88}',500000,2000000,array['Arsenal midfield anchor','England captain','Category slots open'],array['Arsenal''s record signing — central to the club''s ambitions','England captain — World Cup profile building','Multiple category slots available'],array['Adidas holds sportswear'],array['Adidas'],array['Social','Campaign','Appearances']),

('athlete','football','Federico Valverde','Real Madrid · Uruguayan · Age 26','up','14M',array['europe','americas'],true,'{"luxury":72,"sportswear":82,"finance":62,"auto":66,"tech":70,"energy":76,"fmcg":68,"hospitality":66}','{"y1834":58,"female":36,"income":72,"real":88}',400000,1600000,array['Real Madrid regular','South America reach','Category slots open'],array['Real Madrid regular — Champions League winner','Strong South American audience — unique reach for Latin brands','All major category slots available'],array['Building global profile outside South America'],array['Adidas'],array['Social','Campaign']),

('athlete','football','Florian Wirtz','Bayer Leverkusen · German · Age 21','up','16M',array['europe'],true,'{"luxury":72,"sportswear":84,"finance":62,"auto":72,"tech":74,"energy":72,"fmcg":68,"hospitality":66}','{"y1834":66,"female":36,"income":72,"real":90}',500000,2000000,array['Bundesliga MVP','German market','Rising fast'],array['Bayer Leverkusen''s unbeaten season hero — defining German football moment','66% aged 18–34 — strong youth demographic','Potential Real Madrid or Bayern move would massively increase value'],array['Club situation uncertain for next season','Limited global profile outside Germany currently'],array['Adidas'],array['Social','Campaign','Appearances']),

('athlete','football','Jamal Musiala','Bayern Munich · German · Age 21','up','14M',array['europe','asia'],true,'{"luxury":72,"sportswear":84,"finance":62,"auto":74,"tech":74,"energy":72,"fmcg":68,"hospitality":66}','{"y1834":68,"female":36,"income":72,"real":90}',500000,2000000,array['Bayern star','German-English dual market','Rising'],array['Bayern Munich''s brightest talent — dual German-English market reach','68% aged 18–34 — excellent youth demographic','Authentic story — chose Germany over England at youth level'],array['Limited social following','Building global brand'],array['Adidas'],array['Social','Campaign']),

-- ─── TENNIS ATHLETES ──────────────────────────────────────────────────────────
('athlete','tennis','Jannik Sinner','ATP #1 · Italian · Age 23','up','18M',array['europe','asia'],true,'{"luxury":91,"sportswear":88,"finance":79,"auto":83,"tech":85,"energy":74,"fmcg":60,"hospitality":80}','{"y1834":53,"female":48,"income":88,"real":94}',800000,3500000,array['ATP #1','Rising fast','High income audience'],array['World #1 at peak market exposure window','94% real follower rate — best engagement quality in tennis','Fashion-forward Italian persona commands luxury premiums'],array['Doping case in 2024 — cleared but monitor','Lower total following vs football peers'],array['Rolex','Gucci','Lavazza'],array['Social','Appearances','Campaign','Events']),

('athlete','tennis','Carlos Alcaraz','ATP #3 · Spanish · Age 21','up','20M',array['europe','americas','asia'],false,'{"luxury":88,"sportswear":90,"finance":72,"auto":79,"tech":80,"energy":76,"fmcg":70,"hospitality":82}','{"y1834":60,"female":46,"income":84,"real":92}',1000000,3500000,array['Multi-Slam winner','Global reach','46% female'],array['Youngest multi-Grand-Slam winner ever','46% female — best gender split in men''s tennis','Strong luxury, tech and hospitality audience affinity'],array['BMW holds auto','Nike holds sportswear','Rolex holds luxury'],array['Nike','Rolex','BMW'],array['Social','Campaign','Appearances']),

('athlete','tennis','Novak Djokovic','ATP · Serbian · Age 37','down','14M',array['europe','asia'],false,'{"luxury":82,"sportswear":76,"finance":78,"auto":74,"tech":72,"energy":62,"fmcg":64,"hospitality":80}','{"y1834":34,"female":42,"income":90,"real":86}',1200000,4000000,array['Most Slam titles ever','Income score 90','Career twilight premium'],array['24 Grand Slams — unmatched legacy brand association','Income score 90 — highly affluent dedicated global fan base','History-making moments still drive global media'],array['Career wind-down — limited deal duration','2022 vaccine controversy affects some markets'],array['Lacoste','Seiko','Peugeot'],array['Social','Campaign','Appearances']),

('athlete','tennis','Aryna Sabalenka','WTA #1 · Belarusian · Age 26','up','8M',array['europe','americas'],true,'{"luxury":86,"sportswear":88,"finance":72,"auto":76,"tech":74,"energy":76,"fmcg":68,"hospitality":80}','{"y1834":52,"female":62,"income":82,"real":90}',600000,2500000,array['WTA #1','62% female','All categories open'],array['World #1 women''s player — all categories open','62% female audience — premium for brands targeting women','Back-to-back Australian Open wins'],array['Belarus nationality creates sensitivity in some Western markets'],array['Nike','Head'],array['Social','Campaign','Appearances']),

('athlete','tennis','Iga Świątek','WTA · Polish · Age 23','flat','10M',array['europe','americas'],false,'{"luxury":84,"sportswear":86,"finance":70,"auto":74,"tech":76,"energy":72,"fmcg":66,"hospitality":78}','{"y1834":54,"female":60,"income":80,"real":91}',700000,2800000,array['Roland Garros queen','60% female','FMCG affinity'],array['Multiple Roland Garros titles — strongest clay court brand in women''s tennis','60% female audience with strong European demographic'],array['WADA investigation in 2024 — cleared, monitor'],array['Rolex','Tecnifibre','LOTOS'],array['Social','Campaign','Events']),

('athlete','tennis','Coco Gauff','WTA · American · Age 20','up','12M',array['americas','global'],false,'{"luxury":80,"sportswear":90,"finance":68,"auto":70,"tech":84,"energy":76,"fmcg":72,"hospitality":74}','{"y1834":66,"female":58,"income":76,"real":89}',800000,3000000,array['US Open champion','Gen Z icon','Tech score 84'],array['US Open champion — peak American brand equity','66% aged 18–34 — strongest Gen Z reach in women''s tennis','Tech score 84 — authentic digital-native positioning'],array['New Balance and Rolex hold key categories'],array['New Balance','Rolex','Barilla'],array['Social','Campaign','Appearances']),

('athlete','tennis','Daniil Medvedev','ATP · Russian · Age 28','flat','6M',array['europe','asia'],false,'{"luxury":78,"sportswear":80,"finance":70,"auto":72,"tech":74,"energy":68,"fmcg":62,"hospitality":72}','{"y1834":46,"female":38,"income":80,"real":87}',600000,2000000,array['US Open champion','Consistent top 5','Category slots open'],array['US Open champion — consistent Grand Slam contender','Multiple category slots available','Strong European and Asian audience'],array['Russian nationality creates sensitivity in some Western markets'],array['Lacoste','Tecnifibre'],array['Social','Campaign','Appearances']),

('athlete','tennis','Holger Rune','ATP · Danish · Age 21','up','4M',array['europe'],true,'{"luxury":78,"sportswear":82,"finance":64,"auto":68,"tech":72,"energy":70,"fmcg":62,"hospitality":70}','{"y1834":58,"female":44,"income":76,"real":89}',300000,1200000,array['Scandinavian market','Rising star','All slots open'],array['Scandinavia''s biggest tennis talent — unique market positioning','58% aged 18–34 — strong youth demographic','All category slots open — early mover opportunity'],array['Still developing consistency at Grand Slam level'],array['Puma','Babolat'],array['Social','Campaign','Appearances']),

('athlete','tennis','Taylor Fritz','ATP · American · Age 27','up','4M',array['americas'],true,'{"luxury":74,"sportswear":80,"finance":68,"auto":68,"tech":72,"energy":70,"fmcg":64,"hospitality":68}','{"y1834":50,"female":44,"income":76,"real":88}',300000,1200000,array['Top American men''s tennis','US market','Category slots open'],array['Best American men''s tennis player — strong US market positioning','50% aged 18–34 with good gender balance','All category slots available'],array['Limited global recognition outside Americas'],array['Nike','Wilson'],array['Social','Campaign','Appearances']),

('athlete','tennis','Elena Rybakina','WTA · Kazakhstani · Age 25','up','5M',array['asia','europe'],true,'{"luxury":80,"sportswear":82,"finance":68,"auto":70,"tech":70,"energy":68,"fmcg":62,"hospitality":72}','{"y1834":50,"female":58,"income":78,"real":89}',400000,1600000,array['Wimbledon champion','Kazakhstan reach','Category slots open'],array['Wimbledon champion — heritage association with most prestigious Slam','Central Asia market access — unique geographic reach','58% female audience with growing following'],array['Nationality sensitivity in some European markets'],array['Nike','Wilson','SAP'],array['Social','Campaign','Appearances']),

-- ─── GOLF ATHLETES ────────────────────────────────────────────────────────────
('athlete','golf','Rory McIlroy','PGA Tour · Northern Irish · Age 35','flat','22M',array['europe','americas'],true,'{"luxury":90,"sportswear":70,"finance":88,"auto":85,"tech":78,"energy":55,"fmcg":60,"hospitality":88}','{"y1834":28,"female":30,"income":95,"real":90}',1200000,4000000,array['Income score 95','Finance & luxury','Slots open'],array['Highest income audience of any individual athlete — 95/100','Finance and luxury categories fully open','Major champion — consistent year-round media presence'],array['Demographics skew 35+','LIV/PGA tension reduced broadcast reach'],array['Nike','TaylorMade','Optum'],array['Social','Appearances','Campaign','Hospitality']),

('athlete','golf','Scottie Scheffler','PGA Tour · American · Age 27','up','8M',array['americas','europe'],true,'{"luxury":86,"sportswear":72,"finance":84,"auto":82,"tech":72,"energy":58,"fmcg":62,"hospitality":84}','{"y1834":32,"female":28,"income":94,"real":88}',1000000,3500000,array['World #1','Income score 94','Season of decade'],array['World #1 — 2024 season called the best in men''s golf ever','Income score 94 — exceptional affluent audience','Multiple category slots available'],array['Lower social presence limits digital activation'],array['Titleist','Rolex','Under Armour'],array['Social','Campaign','Appearances','Hospitality']),

('athlete','golf','Jon Rahm','LIV Golf · Spanish · Age 29','flat','10M',array['europe','americas'],true,'{"luxury":84,"sportswear":70,"finance":82,"auto":80,"tech":70,"energy":62,"fmcg":64,"hospitality":82}','{"y1834":30,"female":26,"income":92,"real":87}',1000000,3500000,array['Masters champion','LIV Golf','Spanish market reach'],array['Masters champion — elite prestige association','Strong Spanish-speaking market penetration','Income score 92 with open category slots'],array['LIV association divides some traditional golf sponsors'],array['Callaway','Rolex'],array['Social','Campaign','Appearances']),

('athlete','golf','Nelly Korda','LPGA Tour · American · Age 25','up','6M',array['americas','europe'],true,'{"luxury":82,"sportswear":76,"finance":76,"auto":74,"tech":72,"energy":66,"fmcg":68,"hospitality":80}','{"y1834":40,"female":58,"income":88,"real":89}',500000,2000000,array['LPGA #1','58% female','Income score 88'],array['LPGA world #1 — dominant women''s golf story','58% female with very high income score 88','All primary categories available'],array['Women''s golf has smaller broadcast reach than men''s'],array['Titleist','Mizzen+Main'],array['Social','Campaign','Events']),

('athlete','golf','Tommy Fleetwood','PGA Tour · English · Age 33','flat','5M',array['europe','americas'],true,'{"luxury":82,"sportswear":68,"finance":80,"auto":78,"tech":68,"energy":55,"fmcg":58,"hospitality":80}','{"y1834":28,"female":28,"income":90,"real":87}',400000,1600000,array['Ryder Cup icon','UK market','Finance fit'],array['Ryder Cup hero — most beloved European team golfer','Income score 90 — affluent audience','UK market access across golf and lifestyle audience'],array['Individual title drought affects some brand narratives'],array['TaylorMade','Rolex'],array['Social','Campaign','Hospitality']),

('athlete','golf','Justin Thomas','PGA Tour · American · Age 31','flat','5M',array['americas'],true,'{"luxury":80,"sportswear":68,"finance":80,"auto":78,"tech":68,"energy":55,"fmcg":58,"hospitality":78}','{"y1834":28,"female":26,"income":92,"real":86}',400000,1600000,array['Major winner','US market','Finance fit'],array['Two-time Major winner — sustained US market brand equity','Income score 92 — premium American golf audience','Multiple category slots available'],array['Recent performance dip — trajectory watch'],array['Ralph Lauren','Titleist'],array['Social','Campaign','Hospitality']),

('athlete','golf','Brooke Henderson','LPGA · Canadian · Age 26','flat','3M',array['americas','europe'],true,'{"luxury":74,"sportswear":72,"finance":72,"auto":68,"tech":68,"energy":64,"fmcg":68,"hospitality":72}','{"y1834":36,"female":60,"income":78,"real":88}',200000,800000,array['Canada''s golf icon','60% female','Low cost'],array['Canada''s greatest ever golfer — unique national market positioning','60% female audience with strong values alignment','Very accessible price point for premium sport association'],array['Limited global reach outside Canada and Americas'],array['Ping','Rolex'],array['Social','Campaign']),

-- ─── MOTORSPORT ATHLETES ──────────────────────────────────────────────────────
('athlete','motorsport','Max Verstappen','Red Bull Racing · Dutch · Age 27','up','28M',array['global'],false,'{"luxury":84,"sportswear":68,"finance":70,"auto":96,"tech":88,"energy":90,"fmcg":62,"hospitality":82}','{"y1834":52,"female":34,"income":86,"real":88}',3000000,15000000,array['4× World Champion','Auto score 96','Global reach'],array['4 consecutive championships — F1''s dominant narrative','Auto score 96 — highest of any individual athlete','Red Bull platform amplifies across all 23 race weekends'],array['Red Bull and Oracle hold primary categories','Dominant narrative reduces space for partner stories'],array['Red Bull','Oracle','Ford'],array['Social','Campaign','Appearances']),

('athlete','motorsport','Lewis Hamilton','Ferrari · British · Age 40','up','35M',array['global'],true,'{"luxury":90,"sportswear":72,"finance":74,"auto":88,"tech":82,"energy":68,"fmcg":68,"hospitality":86}','{"y1834":46,"female":42,"income":88,"real":87}',4000000,18000000,array['Ferrari move','7× champion','42% female'],array['Ferrari switch — biggest story in F1 history','42% female audience — best in motorsport','7 world championships — deepest brand legacy in the sport'],array['Performance uncertainty in new Ferrari era','Very high pricing floor'],array['IWC','Tommy Hilfiger','Monster'],array['Social','Campaign','Appearances']),

('athlete','motorsport','Charles Leclerc','Ferrari · Monégasque · Age 26','up','18M',array['europe','global'],true,'{"luxury":92,"sportswear":68,"finance":72,"auto":90,"tech":80,"energy":72,"fmcg":62,"hospitality":88}','{"y1834":54,"female":40,"income":90,"real":89}',2000000,8000000,array['Ferrari icon','Luxury score 92','Monaco connection'],array['Ferrari tifosi — most passionate fanbase in motorsport','Monaco connection commands luxury positioning at highest level','Income score 90 with 54% aged 18–34 — rare combination'],array['Richard Mille holds luxury watch','Ferrari limits some category freedom'],array['Richard Mille','Lancel'],array['Social','Campaign','Appearances']),

('athlete','motorsport','Lando Norris','McLaren · British · Age 25','up','22M',array['europe','americas'],false,'{"luxury":78,"sportswear":70,"finance":66,"auto":88,"tech":90,"energy":82,"fmcg":68,"hospitality":76}','{"y1834":62,"female":38,"income":80,"real":90}',1500000,6000000,array['McLaren star','Tech score 90','Best Gen Z in F1'],array['McLaren''s commercial face — fastest growing driver brand in F1','Tech score 90 — authentic gaming and streaming personality','62% aged 18–34 — best youth reach in motorsport'],array['Dell and OKX hold key McLaren categories'],array['Quadrant'],array['Social','Personal campaign','Content']),

('athlete','motorsport','George Russell','Mercedes · British · Age 26','up','12M',array['europe','americas'],true,'{"luxury":78,"sportswear":68,"finance":68,"auto":86,"tech":80,"energy":70,"fmcg":62,"hospitality":76}','{"y1834":50,"female":34,"income":82,"real":88}',1000000,4000000,array['Mercedes leader','UK market','Category slots open'],array['Mercedes team leader post-Hamilton — stepping into the spotlight','Strong UK market with growing global profile','Multiple category slots available'],array['Post-Hamilton transition — performance pressure'],array['Mercedes partners'],array['Social','Campaign','Appearances']),

('athlete','motorsport','Carlos Sainz Jr.','Williams · Spanish · Age 30','flat','14M',array['europe','americas'],true,'{"luxury":78,"sportswear":68,"finance":66,"auto":84,"tech":76,"energy":72,"fmcg":66,"hospitality":74}','{"y1834":50,"female":36,"income":78,"real":87}',800000,3000000,array['Williams leader','Spanish market','Category slots open'],array['Spanish market access — 500M+ Spanish-speaking global audience','Williams rebuild story — strong narrative for challenger brands','Multiple category slots available'],array['Williams performance trajectory uncertain'],array['Estrella Galicia'],array['Social','Campaign','Appearances']),

('athlete','motorsport','Fernando Alonso','Aston Martin · Spanish · Age 43','flat','12M',array['europe','americas'],false,'{"luxury":82,"sportswear":62,"finance":72,"auto":86,"tech":72,"energy":68,"fmcg":62,"hospitality":78}','{"y1834":36,"female":30,"income":84,"real":85}',1200000,4000000,array['F1 legend','Two-time champion','Legacy association'],array['Two-time world champion — deepest legacy in Spanish motorsport','Longevity story unique in F1 — authentic brand for endurance narratives','Strong Spanish and Latin American audience'],array['Age 43 — limited career runway for long-term deals'],array['Aston Martin partners','Kimoa'],array['Social','Campaign','Appearances']),

-- ─── CYCLING ATHLETES ─────────────────────────────────────────────────────────
('athlete','cycling','Tadej Pogačar','UAE Emirates · Slovenian · Age 25','up','12M',array['europe'],true,'{"luxury":78,"sportswear":82,"finance":64,"auto":74,"tech":70,"energy":88,"fmcg":65,"hospitality":72}','{"y1834":44,"female":28,"income":76,"real":93}',600000,2000000,array['Tour de France champion','Category slots open','Endurance audience'],array['Back-to-back Tour de France champion — cycling at peak commercial moment','Open slots in luxury, finance, tech — first mover advantage','Highly engaged audience with strong purchase intent'],array['Smaller following vs ball sport','Cycling demographics skew male 35+'],array['Adidas','Specialized','Ekoi'],array['Kit','Social','Campaign','Events']),

('athlete','cycling','Jonas Vingegaard','Visma-Lease a Bike · Danish · Age 27','flat','6M',array['europe'],true,'{"luxury":72,"sportswear":80,"finance":62,"auto":70,"tech":66,"energy":82,"fmcg":64,"hospitality":68}','{"y1834":40,"female":26,"income":74,"real":91}',400000,1500000,array['Tour de France winner','Scandinavian market','Slots open'],array['Two-time Tour de France champion — Pogačar''s only real rival','Strong Scandinavian market penetration — unique geographic reach','All major category slots available'],array['Recovery from crash — return timing uncertain'],array['Visma','Specialized'],array['Kit','Social','Campaign']),

('athlete','cycling','Mathieu van der Poel','Alpecin-Deceuninck · Dutch · Age 29','up','8M',array['europe'],true,'{"luxury":68,"sportswear":84,"finance":60,"auto":68,"tech":68,"energy":84,"fmcg":66,"hospitality":66}','{"y1834":46,"female":28,"income":72,"real":90}',400000,1500000,array['Multi-discipline champion','Paris-Roubaix winner','Dutch market'],array['Champion across road, cyclocross and mountain bike — unique multi-sport story','Paris-Roubaix and Monument wins — cycling''s most exciting rider','Alpecin title sponsor relationship creates brand-athlete synergy'],array['Cross-discipline niche audience hard to activate broadly'],array['Alpecin','Canyon','SRAM'],array['Kit','Social','Campaign']),

('athlete','cycling','Remco Evenepoel','Soudal Quick-Step · Belgian · Age 24','up','7M',array['europe'],true,'{"luxury":70,"sportswear":80,"finance":62,"auto":68,"tech":68,"energy":80,"fmcg":62,"hospitality":66}','{"y1834":48,"female":28,"income":72,"real":90}',350000,1400000,array['Olympic champion','Belgian market','Rising fast'],array['Olympic time trial champion — peak recognition moment','Belgian cycling hero — passionate domestic fanbase','48% aged 18–34 — strong youth demographic for cycling'],array['Grand Tour results not yet matching Olympic success'],array['Soudal','Specialized'],array['Kit','Social','Campaign']),

-- ─── ATHLETICS ATHLETES ───────────────────────────────────────────────────────
('athlete','athletics','Mondo Duplantis','World Record Holder · Swedish · Age 24','up','9M',array['europe','americas'],true,'{"luxury":72,"sportswear":86,"finance":60,"auto":68,"tech":74,"energy":80,"fmcg":65,"hospitality":65}','{"y1834":52,"female":40,"income":70,"real":91}',300000,1200000,array['Olympic champion','World record','All slots open'],array['World record holder — unique ownable athletic narrative','Olympic gold — sustained global visibility','Lower cost than team sport with high authenticity'],array['Athletics season is short','Niche sport limits mass reach'],array['Nike','Red Bull'],array['Social','Campaign','Appearances','Speaking']),

('athlete','athletics','Noah Lyles','USA Track & Field · American · Age 27','up','8M',array['americas','global'],true,'{"luxury":70,"sportswear":90,"finance":62,"auto":68,"tech":78,"energy":82,"fmcg":68,"hospitality":64}','{"y1834":58,"female":44,"income":68,"real":88}',300000,1200000,array['100m World Champion','Gen Z personality','Open categories'],array['100m World champion — fastest man story','58% aged 18–34 — strong Gen Z and streetwear audience','Outspoken personality with entertainment crossover'],array['100m title retention pressure','Limited European brand recognition'],array['Adidas','Gatorade'],array['Social','Campaign','Appearances']),

('athlete','athletics','Faith Kipyegon','World Record Holder · Kenyan · Age 30','up','4M',array['global','africa'],true,'{"luxury":68,"sportswear":82,"finance":60,"auto":62,"tech":66,"energy":78,"fmcg":70,"hospitality":62}','{"y1834":50,"female":60,"income":64,"real":92}',150000,700000,array['3× Olympic champion','60% female','Values story'],array['3 consecutive Olympic 1500m golds — greatest distance runner ever','60% female audience with authentic purpose narrative','Very low budget for disproportionate global media exposure'],array['Limited commercial following outside athletics community'],array['Nike'],array['Social','Campaign','Appearances']),

('athlete','athletics','Marcell Jacobs','Olympic Champion · Italian · Age 30','flat','5M',array['europe'],true,'{"luxury":78,"sportswear":84,"finance":66,"auto":72,"tech":68,"energy":76,"fmcg":66,"hospitality":70}','{"y1834":52,"female":42,"income":72,"real":89}',200000,800000,array['Olympic 100m champion','Italian market','Luxury fit'],array['Olympic 100m champion — fastest man in the world story','Italian nationality — luxury and auto brand affinity built in','All major category slots available'],array['Injury history limits activation windows'],array['Puma','Oakley'],array['Social','Campaign','Appearances']),

('athlete','athletics','Sifan Hassan','Multiple World Records · Dutch · Age 31','flat','3M',array['europe'],true,'{"luxury":64,"sportswear":78,"finance":58,"auto":58,"tech":62,"energy":76,"fmcg":68,"hospitality":60}','{"y1834":44,"female":58,"income":66,"real":90}',100000,500000,array['Multi-distance champion','Netherlands reach','Low cost'],array['Marathon and track world records — unique multi-distance story','58% female audience with purpose and values alignment','Very low budget for authentic Olympic association'],array['Lower commercial profile outside athletics community'],array['Nike'],array['Social','Campaign']),

-- ─── BADMINTON ATHLETES ───────────────────────────────────────────────────────
('athlete','badminton','Viktor Axelsen','BWF #1 · Danish · Age 30','flat','4M',array['europe','asia'],true,'{"luxury":74,"sportswear":82,"finance":68,"auto":70,"tech":76,"energy":74,"fmcg":68,"hospitality":72}','{"y1834":48,"female":44,"income":76,"real":90}',200000,900000,array['World #1','Olympic champion','Asia-Europe bridge'],array['World #1 and Olympic champion — dominant badminton narrative','Unique bridging audience across Europe and Asia','All major category slots open outside Yonex'],array['Niche sport in Western markets'],array['Yonex','Hummel'],array['Social','Appearances','Campaign']),

('athlete','badminton','An Se-young','BWF WTA #1 · South Korean · Age 22','up','6M',array['asia'],true,'{"luxury":78,"sportswear":82,"finance":68,"auto":68,"tech":80,"energy":72,"fmcg":72,"hospitality":74}','{"y1834":56,"female":62,"income":78,"real":91}',150000,700000,array['Women''s #1','K-culture reach','Tech score 80'],array['Dominant women''s world #1 — peak South Korean sports culture moment','62% female with strong K-culture crossover audience','Tech score 80 — authentic digital-native positioning in Asia'],array['Limited recognition outside Asia'],array['Yonex','Samsung'],array['Social','Campaign','Appearances']),

('athlete','badminton','Tai Tzu-ying','BWF · Taiwanese · Age 29','flat','3M',array['asia'],true,'{"luxury":72,"sportswear":76,"finance":64,"auto":62,"tech":74,"energy":68,"fmcg":68,"hospitality":66}','{"y1834":48,"female":60,"income":72,"real":89}',100000,500000,array['Former world #1','Taiwan market','Strong female audience'],array['Former world #1 — sustained recognition across Asia','60% female audience — strong for brands targeting Asian women','Taiwan market access — underserved in sport sponsorship'],array['Age — career nearing end phase'],array['Yonex'],array['Social','Campaign']),

('athlete','badminton','Lee Zii Jia','BWF · Malaysian · Age 26','up','3M',array['asia'],true,'{"luxury":68,"sportswear":76,"finance":62,"auto":62,"tech":72,"energy":70,"fmcg":68,"hospitality":64}','{"y1834":52,"female":44,"income":68,"real":89}',80000,400000,array['Malaysia icon','Southeast Asia reach','Rising'],array['Malaysia''s biggest badminton star — Southeast Asia market access','52% aged 18–34 — growing youth following','Low cost entry for Southeast Asian brand building'],array['Limited global recognition outside Asia'],array['Yonex'],array['Social','Campaign']),

-- ─── SWIMMING ATHLETES ────────────────────────────────────────────────────────
('athlete','swimming','Caeleb Dressel','USA Swimming · American · Age 27','flat','2M',array['americas'],true,'{"luxury":66,"sportswear":80,"finance":62,"auto":62,"tech":66,"energy":78,"fmcg":66,"hospitality":62}','{"y1834":46,"female":44,"income":68,"real":88}',150000,600000,array['Olympic champion','Multiple gold medals','US market'],array['Multiple Olympic gold medals — peak American sports hero','Multiple category slots available','Family-friendly brand positioning'],array['Swimming has limited year-round media presence','Lower commercial following outside Games'],array['Speedo','TYR'],array['Social','Campaign','Appearances']),

('athlete','swimming','Sarah Sjöström','Swedish · Age 30','flat','2M',array['europe'],true,'{"luxury":68,"sportswear":76,"finance":62,"auto":60,"tech":64,"energy":72,"fmcg":66,"hospitality":62}','{"y1834":44,"female":62,"income":68,"real":89}',100000,500000,array['World record holder','Scandinavian market','60% female'],array['World record holder — sustained elite status over decade','60% female audience — strong for women-targeted brands','Scandinavian market access at very low cost'],array['Limited commercial profile outside swimming community'],array['Arena','Speedo'],array['Social','Campaign']),

-- ─── RUGBY ATHLETES ───────────────────────────────────────────────────────────
('athlete','rugby','Antoine Dupont','France · Scrum Half · Age 27','up','5M',array['europe'],true,'{"luxury":80,"sportswear":80,"finance":68,"auto":72,"tech":68,"energy":74,"fmcg":70,"hospitality":74}','{"y1834":52,"female":36,"income":78,"real":89}',300000,1200000,array['World''s best rugby player','France market','Category slots open'],array['Universally recognised as world''s best player — defining rugby brand story','French market access — premium consumer audience','Multiple category slots available including luxury'],array['Rugby has limited global reach outside traditional markets'],array['Gilbert','Adidas'],array['Social','Campaign','Appearances']),

('athlete','rugby','Richie Mo''unga','All Blacks · New Zealand · Age 30','flat','2M',array['asia','global'],true,'{"luxury":68,"sportswear":76,"finance":62,"auto":62,"tech":66,"energy":70,"fmcg":66,"hospitality":66}','{"y1834":46,"female":32,"income":68,"real":87}',100000,500000,array['All Blacks icon','Pacific reach','Category slots open'],array['All Blacks — most iconic rugby brand globally','Pacific and Asian market access through New Zealand association','Multiple category slots available at low cost'],array['Rugby''s global commercial reach is limited vs football'],array['Adidas','All Blacks partners'],array['Social','Campaign']),

-- ─── CRICKET ATHLETES ─────────────────────────────────────────────────────────
('athlete','cricket','Virat Kohli','India · Batsman · Age 35','flat','270M',array['asia','global'],false,'{"luxury":82,"sportswear":88,"finance":72,"auto":74,"tech":76,"energy":78,"fmcg":84,"hospitality":74}','{"y1834":60,"female":42,"income":72,"real":87}',5000000,20000000,array['270M followers','India reach premium','FMCG powerhouse'],array['270M followers — second only to Cristiano Ronaldo globally','India market access — 1.4B people, fastest growing middle class','FMCG score 84 — strongest consumer goods reach in Asian sport'],array['Multiple category conflicts','Age 35 — career management watch'],array['Puma','MRF','One8'],array['Social','Campaign','Appearances']),

('athlete','cricket','Rohit Sharma','India · Captain · Age 37','flat','50M',array['asia'],false,'{"luxury":76,"sportswear":82,"finance":68,"auto":70,"tech":70,"energy":72,"fmcg":80,"hospitality":68}','{"y1834":54,"female":36,"income":68,"real":85}',2000000,8000000,array['India captain','IPL icon','Retirement imminent'],array['India captain and most beloved cricketer among casual fans','IPL franchise ownership adds commercial versatility','Strong domestic brand equity before retirement'],array['Age 37 — retirement imminent','International career winding down'],array['Adidas','Magnum'],array['Social','Campaign','Appearances']),

('athlete','cricket','Joe Root','England · Batsman · Age 33','flat','5M',array['europe','asia'],true,'{"luxury":72,"sportswear":74,"finance":70,"auto":66,"tech":66,"energy":62,"fmcg":68,"hospitality":68}','{"y1834":40,"female":30,"income":78,"real":87}',200000,900000,array['England''s greatest ever','Record test scorer','Category slots open'],array['England''s all-time leading Test run scorer — sustained elite association','Multiple category slots available at accessible price point','UK and Commonwealth market access'],array['Test cricket has limited global broadcast reach','Lower commercial following vs T20-focused cricketers'],array['New Balance','Dukes'],array['Social','Campaign','Appearances']),

-- ─── BASKETBALL ATHLETES ──────────────────────────────────────────────────────
('athlete','basketball','LeBron James','LA Lakers · American · Age 40','flat','160M',array['global'],false,'{"luxury":84,"sportswear":92,"finance":62,"auto":72,"tech":76,"energy":72,"fmcg":72,"hospitality":72}','{"y1834":52,"female":40,"income":76,"real":86}',20000000,60000000,array['160M followers','GOAT narrative','Multiple conflicts'],array['160M followers — most commercially powerful basketball player ever','SpringHill Company adds media investment dimension','GOAT narrative — legacy brand association secured'],array['Age 40 — career end imminent','Nike holds sportswear exclusively','Many categories already claimed'],array['Nike','Beats','Blaze Pizza','SpringHill'],array['Social','Campaign','Appearances']),

('athlete','basketball','Stephen Curry','Golden State Warriors · American · Age 36','flat','55M',array['global'],false,'{"luxury":82,"sportswear":88,"finance":68,"auto":72,"tech":78,"energy":68,"fmcg":68,"hospitality":72}','{"y1834":48,"female":40,"income":80,"real":87}',8000000,25000000,array['4× champion','Finance fit','Tech audience'],array['4× NBA champion — sustained elite narrative','Finance and tech category affinity strong','55M followers with strong income demographic'],array['Under Armour holds sportswear','Multiple categories claimed'],array['Under Armour','Chase','FTX (resolved)'],array['Social','Campaign','Appearances']),

('athlete','basketball','Giannis Antetokounmpo','Milwaukee Bucks · Greek · Age 29','up','28M',array['global','europe'],true,'{"luxury":76,"sportswear":88,"finance":62,"auto":68,"tech":72,"energy":74,"fmcg":72,"hospitality":68}','{"y1834":54,"female":38,"income":74,"real":88}',5000000,18000000,array['MVP champion','Greek Freak','Multiple slots open'],array['NBA champion and 2× MVP — sustained elite association','Immigrant success story — authentic values brand narrative','Strong European audience particularly in Greece and Germany'],array['Nike holds sportswear','Multiple categories claimed'],array['Nike','Tissot','JBL'],array['Social','Campaign','Appearances']),

('athlete','basketball','Victor Wembanyama','San Antonio Spurs · French · Age 20','up','10M',array['global','europe'],true,'{"luxury":74,"sportswear":88,"finance":56,"auto":60,"tech":80,"energy":72,"fmcg":64,"hospitality":62}','{"y1834":68,"female":38,"income":68,"real":90}',2000000,8000000,array['Once in generation talent','Gen Z icon','Tech fit'],array['Most hyped NBA prospect since LeBron — generational talent narrative','68% aged 18–34 — strongest Gen Z reach in basketball','Tech score 80 — authentic sci-fi personality resonates with digital audience'],array['Nike holds sportswear','Very early career — performance risk'],array['Nike'],array['Social','Campaign']),

-- ─── FOOTBALL CLUBS ───────────────────────────────────────────────────────────
('club','football','Real Madrid CF','La Liga · Spain · Est. 1902','up','1200M',array['global'],false,'{"luxury":88,"sportswear":72,"finance":80,"auto":74,"tech":76,"energy":66,"fmcg":70,"hospitality":84}','{"y1834":54,"female":36,"income":78,"real":87}',5000000,80000000,array['Most followed club globally','Champions League pedigree','Bernabéu digital inventory'],array['1.2B social following — most followed sports club in the world','Champions League record winners — unmatched European prestige','New Bernabéu opens premium digital and tech partnership opportunities'],array['Adidas and Emirates hold most valuable inventory','Top tier prices are institutional budget only'],array['Emirates','Adidas','HP','Santander'],array['Training kit','Digital','Stadium','Hospitality']),

('club','football','FC Barcelona','La Liga · Spain · Est. 1899','up','1100M',array['global'],false,'{"luxury":86,"sportswear":70,"finance":78,"auto":72,"tech":75,"energy":65,"fmcg":68,"hospitality":82}','{"y1834":55,"female":38,"income":74,"real":88}',3000000,40000000,array['1.1B following','44% Asia','Women''s team available'],array['1.1B global following — second only to Real Madrid','44% Asia audience — premier APAC brand entry vehicle','Women''s team available at significant discount to main club deal'],array['Spotify and Nike hold most valuable inventory','FFP constraints limit deal creativity'],array['Spotify','Nike','Mastercard','Stanley'],array['Training kit','Stadium','Digital','Hospitality']),

('club','football','Manchester City FC','Premier League · England · Est. 1880','up','90M',array['europe','asia','americas'],false,'{"luxury":80,"sportswear":72,"finance":76,"auto":74,"tech":82,"energy":68,"fmcg":70,"hospitality":78}','{"y1834":54,"female":36,"income":78,"real":86}',2000000,30000000,array['City Football Group network','Premier League dominant','Tech score 82'],array['City Football Group — global network creates multi-market activation','Tech score 82 — innovation narrative well established','Premier League and Champions League success drives sustained global media'],array['Etihad holds title naming','Premier League financial charges pending'],array['Etihad','Puma','SAP'],array['Training kit','Digital','Hospitality','Stadium']),

('club','football','Arsenal FC','Premier League · England · Est. 1886','up','90M',array['europe','asia','americas'],false,'{"luxury":80,"sportswear":72,"finance":76,"auto":74,"tech":78,"energy":68,"fmcg":70,"hospitality":78}','{"y1834":54,"female":36,"income":78,"real":86}',1500000,20000000,array['Premier League rising','London premium','Growing Asia reach'],array['Title contenders — rising trajectory creates commercial momentum','London association adds premium brand positioning','Strong and growing Asia-Pacific and US fanbase'],array['Emirates and Adidas hold primary inventory'],array['Emirates','Adidas'],array['Training kit','Digital','Matchday','Hospitality']),

('club','football','Paris Saint-Germain','Ligue 1 · France · Est. 1970','flat','120M',array['global'],false,'{"luxury":90,"sportswear":72,"finance":72,"auto":74,"tech":74,"energy":66,"fmcg":66,"hospitality":86}','{"y1834":58,"female":38,"income":80,"real":85}',3000000,40000000,array['Paris luxury positioning','Fashion crossover','Asia-Pacific reach'],array['Paris brand equity unique in football — luxury and fashion crossover natural','Strong Middle East and Asia audience','Multiple commercial tiers available post-Mbappé'],array['Qatar ownership creates sensitivity in some European markets'],array['Nike','QNB','Accor'],array['Training kit','Digital','Stadium','Hospitality']),

('club','football','Borussia Dortmund','Bundesliga · Germany · Est. 1909','up','44M',array['europe','asia'],true,'{"luxury":72,"sportswear":72,"finance":70,"auto":76,"tech":72,"energy":72,"fmcg":72,"hospitality":72}','{"y1834":58,"female":34,"income":72,"real":88}',1000000,12000000,array['Yellow Wall passion','Youth audience 58%','Affordable vs top clubs'],array['The Yellow Wall — most atmospheric stadium in European football','Champions League finalist — peak UCL media exposure','58% aged 18–34 — strong youth brand positioning'],array['Evonik and Puma hold key positions'],array['Evonik','Puma','1&1'],array['Training kit','Stadium','Digital','Hospitality']),

('club','football','Juventus FC','Serie A · Italy · Est. 1897','flat','88M',array['europe','asia','mena'],false,'{"luxury":86,"sportswear":70,"finance":74,"auto":78,"tech":70,"energy":64,"fmcg":66,"hospitality":82}','{"y1834":52,"female":36,"income":78,"real":86}',1500000,18000000,array['Italian luxury positioning','MENA reach','Multiple slots'],array['Italian luxury and fashion brand associations natural fit','Strong MENA and Asia audience from historical star signings','Multiple category slots across luxury, tech, finance'],array['On-field decline after Ronaldo era requires monitoring'],array['Adidas'],array['Training kit','Digital','Stadium','Hospitality']),

('club','football','Bayern München','Bundesliga · Germany · Est. 1900','flat','88M',array['europe','asia'],false,'{"luxury":82,"sportswear":72,"finance":74,"auto":88,"tech":74,"energy":64,"fmcg":68,"hospitality":80}','{"y1834":52,"female":34,"income":80,"real":86}',2000000,30000000,array['Auto score 88','German excellence','Champions League record'],array['Auto category score 88 — strongest of any football club globally','Allianz Arena — one of the world''s premium stadium experiences','Consistent Champions League presence'],array['Audi, Allianz and Adidas hold primary inventory'],array['Allianz','Adidas','Audi','Telekom'],array['Training kit','Stadium','Digital','Hospitality']),

('club','football','Liverpool FC','Premier League · England · Est. 1892','up','90M',array['europe','asia','americas'],false,'{"luxury":80,"sportswear":72,"finance":74,"auto":72,"tech":76,"energy":68,"fmcg":72,"hospitality":78}','{"y1834":54,"female":36,"income":76,"real":86}',2000000,25000000,array['Premier League champions','Global fanbase','Music & culture brand'],array['Premier League champions — sustained elite status','Unique music and culture brand dimension among football clubs','Strong Southeast Asia and Americas fanbase'],array['Standard Chartered and Nike hold primary inventory'],array['Standard Chartered','Nike','Carlsberg'],array['Training kit','Digital','Matchday','Hospitality']),

('club','football','Atlético de Madrid','La Liga · Spain · Est. 1903','up','40M',array['europe','americas'],true,'{"luxury":74,"sportswear":70,"finance":68,"auto":70,"tech":68,"energy":70,"fmcg":68,"hospitality":70}','{"y1834":52,"female":34,"income":72,"real":86}',800000,8000000,array['La Liga contenders','Multiple slots open','Authentic underdog story'],array['Champions League challenger — compelling underdog narrative for brands','Multiple category slots available — less saturated than Barça or Real','Strong South American audience through Spanish-speaking market'],array['Civitas and Nike hold primary positions'],array['Civitas (stadium)','Nike'],array['Training kit','Digital','Hospitality']),

-- ─── F1 TEAMS ─────────────────────────────────────────────────────────────────
('club','motorsport','McLaren F1 Team','Formula 1 · Global · Est. 1963','up','45M',array['global'],true,'{"luxury":88,"sportswear":68,"finance":72,"auto":95,"tech":90,"energy":78,"fmcg":60,"hospitality":86}','{"y1834":48,"female":34,"income":88,"real":90}',5000000,60000000,array['Fastest growing in F1','Tech & luxury slots','180+ markets'],array['F1 audience grew 40% — 1.5B reach annually','Tech and luxury category slots open','Papaya identity — strongest visual brand in F1'],array['Very high entry for premier inventory','Gulf Oil holds energy'],array['Gulf','Dell','OKX','Hilton'],array['Car livery','Hospitality suite','Driver content','Merchandise']),

('club','motorsport','Ferrari F1 Team','Formula 1 · Italy · Est. 1950','up','50M',array['global'],false,'{"luxury":96,"sportswear":62,"finance":72,"auto":96,"tech":80,"energy":70,"fmcg":58,"hospitality":94}','{"y1834":46,"female":36,"income":92,"real":88}',8000000,100000000,array['Luxury score 96','Hamilton era begins','Tifosi passion'],array['Most passionately followed team in sport — global tifosi audience','Luxury score 96 — rivals only Wimbledon and The Masters','Hamilton signing creates biggest F1 story in a generation'],array['Shell and Santander hold key positions','Premium pricing'],array['Shell','Santander','DAZN','Richard Mille'],array['Car livery','Hospitality','Content','Driver access']),

('club','motorsport','Red Bull Racing','Formula 1 · Global · Est. 2005','up','48M',array['global'],false,'{"luxury":78,"sportswear":68,"finance":68,"auto":92,"tech":88,"energy":98,"fmcg":64,"hospitality":80}','{"y1834":52,"female":32,"income":84,"real":89}',6000000,80000000,array['4× champions','Energy score 98','Oracle cloud template'],array['4 consecutive constructors'' championships','Oracle partnership creates template for large-scale tech deals','Energy brand association deeply embedded in DNA'],array['Red Bull holds energy','Verstappen dominance can overshadow partners'],array['Red Bull','Oracle','Ford','Bybit'],array['Car livery','Hospitality','Content','Events']),

('club','motorsport','Mercedes-AMG Petronas F1','Formula 1 · Germany-UK · Est. 2010','flat','42M',array['global'],false,'{"luxury":86,"sportswear":66,"finance":72,"auto":94,"tech":86,"energy":68,"fmcg":60,"hospitality":86}','{"y1834":48,"female":36,"income":88,"real":88}',6000000,75000000,array['7× champions','Lewis Hamilton legacy','Luxury auto fit'],array['7 constructors'' championships — deepest legacy in modern F1','Lewis Hamilton legacy creates sustained cultural authority','Tech and auto category scores both above 85'],array['Post-Hamilton transition creates uncertainty'],array['Petronas','INEOS','Hewlett Packard'],array['Car livery','Hospitality','Content','Driver access']),

-- ─── GOLF CLUBS ───────────────────────────────────────────────────────────────
('club','golf','Ryder Cup Team Europe','Biennial · Pan-European','up','85M',array['europe','americas'],true,'{"luxury":94,"sportswear":72,"finance":88,"auto":86,"tech":72,"energy":60,"fmcg":62,"hospitality":92}','{"y1834":26,"female":32,"income":96,"real":87}',2000000,12000000,array['Income score 96','HNW audience','Finance & luxury slots'],array['Income score 96 — wealthiest audience in team sport globally','Finance, luxury and auto category slots open','Premium hospitality with direct HNW guest access'],array['Age skews 35+ heavily','Biennial only'],array['BMW','Rolex','Radisson'],array['Official partner','Hospitality','Branding','Digital']),

-- ─── TENNIS EVENTS ────────────────────────────────────────────────────────────
('event','tennis','Wimbledon','Grand Slam · London · June–July','flat','400M',array['global'],true,'{"luxury":96,"sportswear":74,"finance":85,"auto":80,"tech":70,"energy":55,"fmcg":65,"hospitality":95}','{"y1834":38,"female":52,"income":92,"real":85}',3000000,25000000,array['Income score 92','52% female','Heritage prestige'],array['Income score 92 — premium audience second only to golf events','52% female — underserved in sport sponsorship','Luxury category has significant open inventory'],array['Conservative brand rules limit activation','Rolex and HSBC hold prominent positions'],array['Rolex','HSBC','IBM','Lanson'],array['Courtside','Hospitality','Digital','Player content']),

('event','tennis','US Open','Grand Slam · New York · August–September','up','380M',array['americas','global'],true,'{"luxury":88,"sportswear":80,"finance":84,"auto":78,"tech":82,"energy":70,"fmcg":72,"hospitality":88}','{"y1834":46,"female":50,"income":88,"real":84}',2500000,20000000,array['New York premium','Finance & tech fit','50% female'],array['New York positioning — financial services and tech natural fit','Most diverse Grand Slam audience — 46% 18–34, 50% female','Night sessions create premium entertainment product'],array['American Express and IBM hold key positions'],array['American Express','IBM','JP Morgan'],array['Courtside','Hospitality','Digital','Player access']),

('event','tennis','Roland Garros','Grand Slam · Paris · May–June','up','360M',array['europe','global'],true,'{"luxury":92,"sportswear":76,"finance":80,"auto":78,"tech":72,"energy":62,"fmcg":68,"hospitality":92}','{"y1834":42,"female":50,"income":90,"real":85}',2500000,20000000,array['Paris luxury positioning','Income score 90','50% female'],array['Paris association commands luxury brand premiums','Income score 90 — affluent European audience at peak summer','Two-week broadcast window in premium media season'],array['BNP Paribas holds finance','Longines and Renault hold key categories'],array['BNP Paribas','Longines','Renault'],array['Courtside','Hospitality','Digital','Player content']),

('event','tennis','Australian Open','Grand Slam · Melbourne · January','up','350M',array['asia','global'],true,'{"luxury":88,"sportswear":78,"finance":80,"auto":76,"tech":80,"energy":68,"fmcg":70,"hospitality":88}','{"y1834":44,"female":48,"income":86,"real":85}',2000000,18000000,array['Asia-Pacific gateway','Tech fit','Season-opener'],array['Season-opening Grand Slam — maximum pre-season media amplification','Strongest Asia-Pacific audience of all four Grand Slams','Melbourne Park expansion creates new commercial inventory'],array['Kia holds auto','ANZ holds finance'],array['Kia','ANZ','Rolex'],array['Courtside','Hospitality','Digital','Content']),

-- ─── GOLF EVENTS ──────────────────────────────────────────────────────────────
('event','golf','The Masters','Augusta National · USA · Annual · April','flat','190M',array['americas','global'],true,'{"luxury":92,"sportswear":65,"finance":90,"auto":82,"tech":68,"energy":50,"fmcg":60,"hospitality":88}','{"y1834":24,"female":28,"income":97,"real":82}',4000000,30000000,array['Income score 97 — highest in sport','Finance fit 90','Extremely limited inventory'],array['Highest income audience of any sporting event globally — 97/100','Finance and luxury category slots available','Green jacket — the most iconic symbol in all of sport'],array['Augusta severely limits broadcast branding','Heavy 45+ age skew'],array['IBM','AT&T','Mercedes-Benz'],array['Official partner','Broadcast limited','Hospitality']),

('event','golf','The Open Championship','R&A · UK venues · Annual · July','flat','180M',array['europe','americas','asia'],true,'{"luxury":90,"sportswear":68,"finance":88,"auto":82,"tech":70,"energy":55,"fmcg":62,"hospitality":88}','{"y1834":26,"female":30,"income":94,"real":83}',3000000,20000000,array['Income score 94','Heritage premium','Rotating British venues'],array['The oldest Major — deepest heritage association in golf','Income score 94 — second only to The Masters','Rotating British venues create varied regional brand opportunities'],array['Age demographic skews 40+','Rolex and Standard Life hold premium positions'],array['Rolex','AIG','Standard Life'],array['On-course','Hospitality','Digital','Broadcast']),

-- ─── MOTORSPORT EVENTS ────────────────────────────────────────────────────────
('event','motorsport','Monaco Grand Prix','Formula 1 · Monaco · Annual · May','up','240M',array['europe','global'],true,'{"luxury":98,"sportswear":60,"finance":86,"auto":88,"tech":76,"energy":65,"fmcg":55,"hospitality":96}','{"y1834":44,"female":35,"income":94,"real":83}',1500000,18000000,array['Luxury score 98 — highest in database','Income score 94','Hospitality icon'],array['Highest luxury fit score of any property in our database — 98/100','Income score 94 — ultra-HNW concentration in Monaco','Superyacht and paddock hospitality for premier client entertainment'],array['One race only — very short activation window'],array['Richard Mille','Tag Heuer','UBS'],array['Paddock','Hospitality','Trackside','Content']),

('event','motorsport','British Grand Prix · Silverstone','Formula 1 · UK · Annual · July','up','200M',array['europe','global'],true,'{"luxury":82,"sportswear":68,"finance":78,"auto":88,"tech":84,"energy":76,"fmcg":68,"hospitality":84}','{"y1834":50,"female":36,"income":84,"real":87}',1000000,12000000,array['Tech & finance fit','UK audience frenzy','Award-winning hospitality'],array['Biggest British sporting event behind the FA Cup final','Strong tech and finance audience','Silverstone Wing hospitality — award-winning client experience'],array['Many F1 calendar slots compete for same budgets'],array['DHL','Lenovo','Hilton'],array['Trackside','Hospitality','Content','Activation']),

-- ─── CYCLING EVENTS ───────────────────────────────────────────────────────────
('event','cycling','Tour de France','ASO · France · Annual · July','up','280M',array['europe','global'],true,'{"luxury":80,"sportswear":78,"finance":72,"auto":76,"tech":74,"energy":86,"fmcg":70,"hospitality":78}','{"y1834":42,"female":36,"income":80,"real":85}',800000,8000000,array['21-day broadcast','12M roadside spectators','Viewership +35%'],array['21 consecutive broadcast days — unmatched sustained exposure in sport','12M+ live roadside spectators annually','Viewership up 35% in three years — fastest growing major European event'],array['Doping history creates brand association risk','Primarily European audience'],array['LCL','Skoda','Leclerc','Aldi'],array['Caravan','Official partner','Broadcast','Team kit']),

('event','cycling','Giro d''Italia','RCS Sport · Italy · Annual · May','up','180M',array['europe'],true,'{"luxury":84,"sportswear":76,"finance":70,"auto":76,"tech":70,"energy":82,"fmcg":70,"hospitality":76}','{"y1834":40,"female":34,"income":80,"real":84}',500000,4000000,array['Italian prestige','Luxury fit','Less saturated than Tour'],array['Italian landscape creates natural luxury brand association','Lower price vs Tour de France with comparable European reach','Multiple category slots available'],array['Smaller global reach than Tour de France'],array['EOLO'],array['Maglia Rosa sponsor','Official partner','Broadcast']),

-- ─── ATHLETICS EVENTS ─────────────────────────────────────────────────────────
('event','athletics','World Athletics Championships','Biennial · Global host city','up','350M',array['global'],true,'{"luxury":72,"sportswear":88,"finance":68,"auto":70,"tech":78,"energy":82,"fmcg":72,"hospitality":68}','{"y1834":52,"female":48,"income":72,"real":86}',1000000,10000000,array['350M reach','48% female','Open categories'],array['350M reach — second only to FIFA in athletics','48% female — best gender balance in mainstream sport','Multiple category slots open — unsaturated vs football'],array['Athletics commercially underperforms vs ball sports'],array['Asics','Omega','Toyota'],array['Official partner','Broadcast','Athlete content','Stadium']),

('event','athletics','Diamond League Series','World Athletics · Global · Annual','up','120M',array['global'],true,'{"luxury":70,"sportswear":84,"finance":66,"auto":68,"tech":76,"energy":80,"fmcg":68,"hospitality":68}','{"y1834":50,"female":46,"income":70,"real":88}',300000,3000000,array['14 global cities','Season-long','Title naming available'],array['14 premium city markets — Dubai, Zurich, Monaco, Tokyo, New York','Season-long activation across May–September','Title naming rights available in select meets'],array['Individual meets have lower reach than championships'],array['Wanda Group','Omega'],array['Title meets','Broadcast','On-field','Content']),

-- ─── FOOTBALL EVENTS ──────────────────────────────────────────────────────────
('event','football','UEFA Champions League Final','UEFA · Annual · May','up','600M',array['global'],true,'{"luxury":86,"sportswear":74,"finance":80,"auto":78,"tech":78,"energy":72,"fmcg":76,"hospitality":86}','{"y1834":58,"female":38,"income":78,"real":84}',5000000,50000000,array['600M one-night reach','Premium hospitality','Category exclusive'],array['600M viewers for the final alone — single highest reach night in club football','Premium hospitality tiers in each host city','Category exclusivity within tier guaranteed'],array['Heineken and Mastercard hold major positions','Very high budget floor'],array['Heineken','Mastercard','PlayStation'],array['Broadcast perimeter','Hospitality','Content','Trophy']),

('event','football','FIFA World Cup 2026','FIFA · USA/Canada/Mexico · June–July 2026','up','5000M',array['global'],true,'{"luxury":82,"sportswear":76,"finance":78,"auto":76,"tech":76,"energy":74,"fmcg":78,"hospitality":82}','{"y1834":58,"female":40,"income":74,"real":82}',10000000,200000000,array['5B reach','Largest event in sport','USA host market'],array['5B+ reach — largest single event in the history of sport','USA host market opens unprecedented North American commercial opportunity','48-team expansion increases duration and touchpoints'],array['Adidas, Coca-Cola, Visa hold top FIFA partner tier','Once every 4 years — long-horizon planning only'],array['Adidas','Visa','Coca-Cola','Qatar Airways'],array['Top tier partner','Broadcast','Stadium','Content']),

-- ─── FOOTBALL LEAGUES ─────────────────────────────────────────────────────────
('league','football','UEFA Champions League','UEFA · Pan-European · Annual','up','1800M',array['global'],true,'{"luxury":84,"sportswear":72,"finance":78,"auto":80,"tech":76,"energy":70,"fmcg":75,"hospitality":80}','{"y1834":58,"female":38,"income":78,"real":86}',20000000,120000000,array['1.8B reach','Season-long','Category exclusive'],array['1.8B annual reach — most watched annual competition globally','Season-long across 32 clubs and 8 months','Category exclusivity guaranteed within tier'],array['Top tier requires institutional budget','Heineken, PlayStation, Mastercard hold prime positions'],array['Heineken','PlayStation','Mastercard','Pepsi'],array['Perimeter','Broadcast','Digital','Trophy']),

('league','football','Premier League','PL · England · Annual','up','1200M',array['global'],false,'{"luxury":78,"sportswear":74,"finance":76,"auto":74,"tech":76,"energy":70,"fmcg":75,"hospitality":76}','{"y1834":55,"female":36,"income":76,"real":85}',5000000,50000000,array['190 countries broadcast','Season-long','Multiple tiers'],array['Most watched football league globally — 190 countries','Official partner tiers available below title level','Strong Asia-Pacific commercial rights package'],array['EA Sports, Nike, Barclays dominate perimeter'],array['EA Sports','Nike','Barclays','Cadbury'],array['Broadcast','Perimeter','Digital','Trophy']),

('league','football','La Liga','RFEF · Spain · Annual','up','800M',array['global'],true,'{"luxury":82,"sportswear":72,"finance":74,"auto":72,"tech":74,"energy":68,"fmcg":70,"hospitality":78}','{"y1834":55,"female":36,"income":74,"real":86}',4000000,30000000,array['Real Madrid & Barça','Latin America 350M','Title naming available'],array['Real Madrid and Barça make La Liga the most watched non-EPL league','Dominant Latin America audience — 350M+ Spanish-speaking market','Title naming rights available'],array['LaLiga brand still building outside Spanish-speaking markets'],array['EA Sports','Santander','Renault'],array['Title naming','Broadcast','Digital','Trophy']),

('league','football','Bundesliga','DFL · Germany · Annual','flat','600M',array['europe','asia'],true,'{"luxury":76,"sportswear":72,"finance":74,"auto":86,"tech":74,"energy":68,"fmcg":72,"hospitality":74}','{"y1834":52,"female":34,"income":76,"real":87}',3000000,20000000,array['Auto score 86','German engineering narrative','Affordable vs EPL'],array['Auto category score 86 — natural German engineering brand fit','Most affordable top-division stadium entry in Europe','DFL MediaHouse creates innovative digital brand opportunities'],array['Allianz and BMW hold key positions'],array['DFL/Allianz','BMW','Telekom'],array['Title associate','Broadcast','Digital','Stadium']),

('league','football','Serie A','FIGC · Italy · Annual','flat','500M',array['europe','americas'],true,'{"luxury":84,"sportswear":70,"finance":72,"auto":78,"tech":70,"energy":64,"fmcg":68,"hospitality":80}','{"y1834":50,"female":34,"income":76,"real":85}',2000000,15000000,array['Italian luxury fit','Fashion audience','Title available'],array['Italian luxury and fashion brand association natural at league level','Title naming available','Strong Italian diaspora in Americas adds geographic reach'],array['Serie A global reach declining vs Premier League'],array['Enilive (title)','EA Sports'],array['Title naming','Broadcast','Digital','Hospitality']),

-- ─── TENNIS LEAGUES ───────────────────────────────────────────────────────────
('league','tennis','ATP Tour Official Partner','ATP · Global · Year-round','up','320M',array['global'],true,'{"luxury":88,"sportswear":80,"finance":80,"auto":76,"tech":82,"energy":70,"fmcg":65,"hospitality":84}','{"y1834":46,"female":46,"income":88,"real":87}',2000000,15000000,array['Year-round 65+ events','Income score 88','46% female'],array['Year-round activation across 65+ events in 30 countries','Best income audience of any tour sport (88)','46% female — best gender balance in top-tier men''s sport'],array['Rolex and Infosys hold key positions'],array['Rolex','Infosys','BOSS','Pepperstone'],array['On-court','Player content','Digital','Broadcast']),

('league','tennis','WTA Tour Official Partner','WTA · Global · Year-round','up','220M',array['global'],true,'{"luxury":86,"sportswear":82,"finance":76,"auto":72,"tech":80,"energy":68,"fmcg":70,"hospitality":82}','{"y1834":48,"female":62,"income":84,"real":88}',1500000,10000000,array['62% female audience','Year-round','Income score 84'],array['62% female audience across 50+ events globally','Year-round — unique sustained female sports platform','All major category slots available outside existing partners'],array['Smaller reach than ATP','Saudi ownership raises governance sensitivity'],array['Hologic (title)'],array['On-court','Player content','Digital','Broadcast']),

-- ─── GOLF LEAGUES ─────────────────────────────────────────────────────────────
('league','golf','PGA Tour Official Partner','PGA Tour · USA-Global · Annual','flat','200M',array['americas','global'],true,'{"luxury":88,"sportswear":68,"finance":90,"auto":84,"tech":76,"energy":58,"fmcg":62,"hospitality":88}','{"y1834":26,"female":28,"income":94,"real":86}',3000000,25000000,array['Income score 94','Finance fit 90 — highest of any tour','USA dominant reach'],array['Highest finance category fit of any tour — 90/100','Income score 94 — wealthiest tour audience globally','Pro-am and hospitality create direct HNW client access'],array['LIV Golf fragmented some star athlete attendance','FedEx and Rolex hold major positions'],array['FedEx','Rolex','BMW','Charles Schwab'],array['Title meets','Broadcast','Hospitality','Pro-am']),

('league','golf','DP World Tour','European Tour · Global · Season-long','up','120M',array['europe','asia','mena'],true,'{"luxury":88,"sportswear":68,"finance":86,"auto":82,"tech":74,"energy":60,"fmcg":60,"hospitality":88}','{"y1834":28,"female":30,"income":92,"real":85}',3000000,20000000,array['Income score 92','Title naming available','MENA & Asia events'],array['Title naming rights available — rare at this level','Income score 92 across 40+ events globally','Events in MENA, Asia, Europe — ideal for new market entry'],array['LIV Golf created viewer fragmentation','Older demographic'],array['DP World','Rolex','HSBC'],array['Title naming','Broadcast','Pro-am','Hospitality']),

('league','golf','LIV Golf League','LIV Golf · Global · Annual','up','80M',array['global','mena'],true,'{"luxury":84,"sportswear":66,"finance":80,"auto":78,"tech":72,"energy":64,"fmcg":60,"hospitality":84}','{"y1834":36,"female":28,"income":90,"real":84}',2000000,15000000,array['Major names','Disrupting golf','MENA reach','Slots open'],array['Top names — Dustin Johnson, Jon Rahm, Bryson DeChambeau','Aggressive global expansion into MENA, USA and Asia','Category slots significantly less saturated than PGA Tour'],array['Political sensitivity around Saudi Arabian backing','Some traditional golf brand resistance'],array['Saudi PIF'],array['Team naming','Broadcast','Hospitality','Activation']),

-- ─── MOTORSPORT LEAGUES ───────────────────────────────────────────────────────
('league','motorsport','Formula 1 Official Partner','F1 · Global · Annual','up','1500M',array['global'],true,'{"luxury":88,"sportswear":66,"finance":74,"auto":92,"tech":88,"energy":76,"fmcg":62,"hospitality":88}','{"y1834":50,"female":36,"income":88,"real":87}',15000000,100000000,array['1.5B reach','23 race weekends','Category exclusive'],array['1.5B annual cumulative reach across 23 race weekends','Drive to Survive drove 40% new audience — younger and more female','Season-long across 23 premium global city markets'],array['Top tier pricing is institutional','Rolex, DHL, Pirelli hold prominent positions'],array['Rolex','DHL','Pirelli','Aramco'],array['Perimeter','Broadcast','Hospitality','Content']),

('league','motorsport','MotoGP Official Partner','Dorna Sports · Global · Annual','up','400M',array['europe','asia'],true,'{"luxury":78,"sportswear":70,"finance":68,"auto":90,"tech":80,"energy":84,"fmcg":66,"hospitality":76}','{"y1834":54,"female":32,"income":76,"real":86}',3000000,20000000,array['400M reach','Asia concentration','Energy & auto fit'],array['400M reach with major Asian concentration — India, Indonesia, Thailand growing fast','Energy and auto category scores both above 80','Less expensive than F1 with comparable Asian reach'],array['Michelin and Tissot hold key categories'],array['Tissot','Michelin','Monster Energy'],array['Perimeter','Broadcast','Hospitality','Content']),

-- ─── CYCLING LEAGUES ──────────────────────────────────────────────────────────
('league','cycling','UCI WorldTour','UCI · Global · Year-round','up','320M',array['europe','global'],true,'{"luxury":76,"sportswear":80,"finance":68,"auto":72,"tech":72,"energy":84,"fmcg":68,"hospitality":72}','{"y1834":42,"female":34,"income":78,"real":88}',1000000,8000000,array['Season-long','Grand Tour access','Rising viewership'],array['Season-long across Tour, Giro, Vuelta and 30+ other races','Viewership rising fastest in 25–44 affluent male demographic','Multiple category slots available'],array['Doping heritage creates ongoing brand risk'],array['Trek','Specialized'],array['Official partner','Broadcast','Team kit association','Digital']),

-- ─── BADMINTON LEAGUES ────────────────────────────────────────────────────────
('league','badminton','BWF World Tour','BWF · Global · Year-round','up','500M',array['asia','europe'],true,'{"luxury":72,"sportswear":82,"finance":68,"auto":66,"tech":80,"energy":74,"fmcg":74,"hospitality":68}','{"y1834":50,"female":48,"income":72,"real":89}',500000,5000000,array['500M reach Asia-dominant','48% female','Tech score 80'],array['500M reach predominantly in Asia — highest-value growth market globally','48% female — excellent gender balance','Tech score 80 — mobile-first Asian audience is key demo for tech brands'],array['Limited Western broadcast reach'],array['HSBC','Yonex'],array['Title tournaments','Broadcast','Digital','Hospitality']),

-- ─── GRASSROOTS ───────────────────────────────────────────────────────────────
('grassroots','football','Common Goal Initiative','Global · NGO · Year-round','up','40M',array['global'],true,'{"luxury":70,"sportswear":80,"finance":72,"auto":68,"tech":74,"energy":70,"fmcg":78,"hospitality":68}','{"y1834":62,"female":50,"income":70,"real":95}',50000,500000,array['Purpose-led','62% under 35','Lowest cost entry'],array['200+ professional players pledge 1% of salary — authentic at scale','62% aged 18–34 — strongest youth skew in database','Ideal for ESG-committed brands — values story built in'],array['Limited broadcast reach','Requires genuine commitment'],array['Adidas','Mastercard'],array['Campaign co-creation','Digital','Player access','Events']),

('grassroots','football','Women''s Football Foundation','National · UK-based · Year-round','up','15M',array['europe'],true,'{"luxury":68,"sportswear":82,"finance":70,"auto":64,"tech":72,"energy":74,"fmcg":80,"hospitality":66}','{"y1834":60,"female":72,"income":68,"real":93}',80000,600000,array['72% female','ESG narrative','Growing fast'],array['72% female audience — highest of any property in database','Strong ESG narrative for gender equity commitments','Women''s football viewership growing 25% per year'],array['Limited broadcast reach','Multi-year commitment needed'],array['Barclays','SSE','Boots'],array['Official partner','Events','Athlete content','Digital']),

('grassroots','athletics','World Athletics Heritage Tour','World Athletics · Global · Annual','up','60M',array['global'],true,'{"luxury":76,"sportswear":80,"finance":70,"auto":68,"tech":72,"energy":78,"fmcg":70,"hospitality":72}','{"y1834":54,"female":46,"income":74,"real":90}',200000,2000000,array['Global cities','First mover','Category open'],array['Live events in Tokyo, NYC, Zurich, Brussels — premium city markets','All category slots open — genuine first-mover advantage','Authentic grassroots story alongside world-class competition'],array['Athletics niche vs football and tennis'],array['Asics','Omega'],array['Title sponsor tier','Branding','Athlete access','Digital']),

('grassroots','golf','Golf Foundation Access Programme','Golf Foundation · Europe · Year-round','up','8M',array['europe'],true,'{"luxury":72,"sportswear":66,"finance":80,"auto":74,"tech":70,"energy":60,"fmcg":68,"hospitality":76}','{"y1834":50,"female":42,"income":70,"real":92}',40000,300000,array['Youngest golf audience','City-focused','Very low cost'],array['50% aged 18–34 — youngest golf audience of any property','Very low budget — high earned media potential','Finance narrative built in — financial literacy programme component'],array['Niche reach — not for visibility-first objectives'],array['DP World','BMW UK'],array['Title naming','Integration','Events','Stories']),

('grassroots','football','Street Child World Cup','Street Child United · Global · Quadrennial','up','25M',array['global'],true,'{"luxury":62,"sportswear":76,"finance":68,"auto":60,"tech":70,"energy":68,"fmcg":74,"hospitality":62}','{"y1834":58,"female":46,"income":62,"real":94}',50000,400000,array['UN-backed','Global media','Authentic purpose'],array['UN-backed — automatic credibility and media amplification','Global media coverage disproportionate to budget invested','58% aged 18–34 — broad youth brand association'],array['Sensitive subject requires careful brand tone','Limited reach between quadrennial events'],array['Adidas','Kiyan Prince Foundation'],array['Title partner','Campaign','Digital','Events']),

('grassroots','tennis','Tennis Foundation Serves Up','Lawn Tennis Assoc. · UK · Year-round','up','10M',array['europe'],true,'{"luxury":72,"sportswear":76,"finance":72,"auto":68,"tech":74,"energy":70,"fmcg":72,"hospitality":72}','{"y1834":52,"female":52,"income":74,"real":91}',60000,400000,array['200,000+ young people','52% female','Wimbledon ecosystem'],array['Programme reaches 200,000+ young people through UK schools annually','52% female — excellent gender balance','LTA affiliation creates Wimbledon ecosystem association at fraction of price'],array['Limited media coverage vs main tour'],array['LTA partners'],array['Programme naming','Digital','Events','School branding']),

('grassroots','cycling','Cycling UK Community Programme','Cycling UK · UK-Europe · Year-round','up','12M',array['europe'],true,'{"luxury":66,"sportswear":78,"finance":68,"auto":64,"tech":72,"energy":78,"fmcg":72,"hospitality":66}','{"y1834":48,"female":44,"income":72,"real":90}',50000,350000,array['Sustainability story','Urban affluent audience','ESG fit'],array['Sustainability narrative increasingly important for brand ESG reporting','Urban commuter audience — affluent, educated, values-driven','Strong fit for tech, energy and FMCG brands targeting sustainability-conscious consumers'],array['Limited media reach','UK-centric geography'],array['Halfords'],array['Programme naming','Events','Digital','Community']),

('grassroots','football','Laureus Sport for Good','Laureus Foundation · Global · Year-round','up','50M',array['global'],true,'{"luxury":78,"sportswear":74,"finance":74,"auto":72,"tech":72,"energy":68,"fmcg":72,"hospitality":74}','{"y1834":52,"female":48,"income":76,"real":90}',200000,2000000,array['200+ ambassador athletes','Global cities','Luxury-adjacent'],array['Ambassador network of 200+ sporting legends — built-in media amplification','Annual Laureus World Sports Awards — high-profile global media event','Luxury-adjacent positioning through founding brands'],array['Mercedes-Benz and Richemont founding role limits category freedom'],array['Mercedes-Benz','Richemont','Moët Hennessy'],array['Official partner','Awards event','Ambassador access','Digital']),

('grassroots','motorsport','Formula E Community Programme','Formula E · Global Cities · Annual','up','35M',array['global'],true,'{"luxury":78,"sportswear":66,"finance":72,"auto":82,"tech":88,"energy":76,"fmcg":64,"hospitality":74}','{"y1834":56,"female":40,"income":80,"real":88}',150000,1200000,array['Sustainability first','Tech score 88','City centres globally'],array['Electric motorsport — sustainability built into product narrative','Races in city centres: London, Monaco, NYC, Tokyo, São Paulo','Tech score 88 — strongest grassroots tech property in database'],array['Still building awareness vs F1','Viewer numbers still growing'],array['Allianz','Julius Baer','ABB'],array['Official partner','Community activation','Digital','Race day']),

('grassroots','athletics','IAAF Kids Athletics','World Athletics · Global · Year-round','up','20M',array['global'],true,'{"luxury":60,"sportswear":80,"finance":64,"auto":60,"tech":68,"energy":72,"fmcg":78,"hospitality":60}','{"y1834":30,"female":52,"income":62,"real":92}',80000,600000,array['6M+ children','Family FMCG fit','150+ countries'],array['6M+ children participate annually across 150+ countries','52% female audience driven by parents and young girls','FMCG and sportswear brand fit strong — family-first positioning'],array['Reach skews to developing markets with lower purchasing power','Activation with children requires careful compliance'],array['Nestlé','Asics'],array['Title sponsor','School programme','Digital','Events']);
